### ISSUE TITLE
Toolbar button image is large, complete toolbar in many states

### ISSUE THREAD

**Issue by whatif** [codebutler/firesheep#103]
The button to bring up Firesheep looks like a complete toolbar, including forward/back/stop/refresh/home/downloads/history/bookmarks/print/newTab/newWindow/cut/copy/paste/fullScreen/historyEnhancedBack/Forward, and those are arranged in five rows simulating various lighting.  It looks like this is just the image file for the default FF toolbar buttons.
Minor bugfix/enhancement to change this image to one resembling a sheep.
I have what is reported the latest versions, Firesheep 0.1 and FF 3.6.13.

**Comment by codebutler** [comment]
This was actually fixed a while ago, but there has not been another release yet.
https://github.com/codebutler/firesheep/commit/ea1130b8984690a46727c1f61884a25f9a4095e0
