### ISSUE TITLE
Yahoo, Google, Facebook and GitHub don't seem to work (anymore?)

### ISSUE THREAD

**Issue by TerrorFactor** [codebutler/firesheep#106]
Hi,
after messing around a bit with the program on my own pc and home network, I noticed that not all websites seem to work.
I've successfully captured login info from a slightly adapted facebook-file, and some others that I made, local and remote. Google doesn't seem to work(although it did at first if I remember correct, ~12 hours ago)(doesn't capture it), the standard fb also doesn't work anymore(removing 'sid' as cookie seemed to help, it's not necessary)(doesn't capture it), nor does github(doesn't capture it). Yahoo seemed to work(it captures it), but it doesn't login.

There are many others that I didn't try, so there might be more. Is someone else experiencing this, or is it me lol?
I'm running on win7 32 bit, with an intel 4965AGN wifi card, with the latest winpcap drivers and firefox 3.6.13.

EDIT: just started chrome(local), it captured my google account, however, I could not log in. It seems that something is messing up somehow.

EDIT 2: only saw your message now that this site is strictly for bugreports. I'm guessing this is some sort of bug, but I've also posted this message on the google board.

**Comment by codebutler** [comment]
GitHub doesn't work anymore because they actually improved their security. The rest I'm not sure and will look into.

**Comment by TerrorFactor** [comment]
Gmail(GX cookie) doesn't seem to work anymore. It seems that gmail uses SSL as standard now, only if you disable that in your options, it works. Google still gets captured, and seems to work, even with ssl enabled in gmail. I should try if it's possible to change the google-cookies to work with gmail.
Facebook still works, but you have to remove 'SID' from the handler.
Could you confirm this?

Great job btw, you've fixed issues(well, on some sites) that were there for way too long!

**Comment by codebutler** [comment]
Thanks, and the Facebook handler has been updated.
