### ISSUE TITLE
Firesheep not compatable with Firefox 3.6.2

### ISSUE THREAD

**Issue by BennyChiu** [codebutler/firesheep#107]
I am trying to install Firesheep and I am running Firefox 3.6.2.
Even the required system said - Firefox 3.6.12 or newer, I got this error message =

Incompatable Extension
 Firesheep 0.1 could not be installed because it is not compatible with Firefox 3.6.2.

**Comment by codebutler** [comment]
I don't understand the problem, install 3.6.12.
