### ISSUE TITLE
Typo in readme (Ubuntu section)

### ISSUE THREAD

**Issue by gmile** [codebutler/firesheep#108]
The following line contains an error:
`sudo apt-get install autconf libtool libpcap-dev libboost-all-dev libhal-dev xulrunner-1.9.2-dev`

Error is as following:
`autconf` -> `autoconf`

**Comment by codebutler** [comment]
Fix typo in readme. Closed by e1439cddd7ec8df72f840f57cb4f1425586c7dc8, #101, and #99.
