### ISSUE TITLE
http-parser directory is empy on Intel Mac 10.6 build

### ISSUE THREAD

**Issue by ParkerK** [codebutler/firesheep#109]
I've been trying to get firesheep to build for hours. I can get the configure done, but `make` starts yelling about how there's issues with:

`No rule to make target`deps/http-parser/http_parser.c'`

**Comment by ParkerK** [comment]
Also, I'm not sure if firesheep-0.1-1.xpi is up to date with the latest source code changes

**Comment by onuisx** [comment]
If you look on GitHub under deps/http-parser there is a link to another project. Just download the files and put them into your local directory

**Comment by clawfire** [comment]
Onuisx nop, the project have been moved away. Must remake the link !

so please reopen the issue
