### ISSUE TITLE
backend exited with error1 for firesheep

### ISSUE THREAD

**Issue by shyguy-zz** [codebutler/firesheep#11]
I along with a small body of people are having problems with the error code above.
i have installed the programs needed, when i start capturing i don't seem to be actually doing so, when i stop capturing i receive the above message. support would be much appreciated

**Comment by TrevorReznik** [comment]
I have the same problem, I get "Backend exited with error 1" and I couldn't find where the error code is describe. Is there any doc on this ? I use Firefox 3.6.11 on Windows 7 32bits
I would appreciate if someone know something about this issue :)

**Comment by OhhhMANA** [comment]
Yh, this keeps happening to me too, i also are using firefox 3.6.11 but on windows 7 64bit

PLEASE HELP!! :)

**Comment by ilovesurfing** [comment]
Same issue. Currently using 64 bit windows 7. 

I installed WinPcap no problem. I then installed the extension without a problem. Everything seems to be working fine, but after I let it sit and run for a while and tested out another computer on the network to see if it worked nothing came up in the scan. I was testing Facebook so I know it is supported. So anyway after nothing came up I stopped capturing and the little message saying "backend exited with error 1" message came up. Any help would be appreciated.

Thanks

**Comment by starslinger72** [comment]
I had this same error occure, sadly im not on that comp so Im not sure which version of firefox I was using.  One thing I did notice was it was capturing all of the data coming through my computer, so I checked things like google and facebook on another instance of firefox and it saw them fine, but did not see my other computer doing the same thing.

**Comment by DaDubbs** [comment]
I got the same error.  I am running Windows 7 X64 and Firefox 3.6.11.

**Comment by farhanmansoor** [comment]
I got this error "Backend exited with error 1." on both my machines. Installed WinPcap, then installed this add-on. All it seems to do is capture the activity on the same computer regardless of whatever is done on the other. I used both the following machines, once as victim and once as attacker, on a NETGEAR unsecured wireless router. 

Machine 1: Windows 7 Enterprise (32 bit) with Firefox 3.6.11. The network cards used Atheros AR5007EG Wireless & Marvell Yukon 88E8039 PCI-E Fast Ethernet.

Machine 2: Windows Vista Home Premium (32 bit) with Firefox 3.6.11. The network cards used Intel WIFI Link 5100 AGN & Realtek PCIe GBE Family Controller

The peculiar thing I noticed on both machines was that the Interface tab (preferences) showed only the Wired LAN cards by their respective names. The wireless cards were denoted by the word "Microsoft"

**Comment by ilovesurfing** [comment]
Yeah... so basically I was tinkering a little more and realized that it had my WLAN card selected as well. What is odd though is that, like the above post, there are two options for "Microsoft" for the other interfaces. I am running Windows 7 64bit.

I will keep messing with it and check back here in a little bit.

**Comment by ilovesurfing** [comment]
still no luck :(

**Comment by kstevens** [comment]
See this error every time I press "Stop Capturing".  Windows 7x64, Firefox 3.6.11, WinPcap 4.1.2

**Comment by clinton4** [comment]
I also have this problem when i press "Stop Capturing". I'am using Win XP home (service pack 3), Firefox 3.6.11, WinPcap 4.1.2.

**Comment by Graurk** [comment]
Also have this problem running Win 7 32 bit, FF 3.6.10.

I used Wireshark (http://www.wireshark.org/) to figure out what to use for the wireless, which happened to be my the first microsoft. However when connected with Ethernet cable it shows that i am using what Firesheep says is network connection.

**Comment by farhanmansoor** [comment]
Refering to Issue# 36 Firesheep on Windows 7. There is a solution provided there. I tried and it worked fine, although still with the backend exited error... 

Thought I should let you guys know...

**Comment by 3keepmovingforward3** [comment]
SEMI-FIX
I changed my preferences->capture to windows, it works now, but still gives the error

**Comment by codebutler** [comment]
Hello,

This error is displayed incorrectly after clicking the "Stop Capturing" button and can be ignored, it is not indicating a real problem.

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!

**Comment by namu92** [comment]
to make the "backend exited with error 1" to stop you have to go to preference>advance>and change the word to tc port to which windows version you have like mines is 7 so you put 07. if your computer is windows 98 you put tc port 98. thats stops the error from happening. for more bug and computer problems visit us at koraglitch.com

**Comment by dxcsksans** [comment]
@namu92 sir..im using windows xp...so to wat number shuld i change ????pls help me.....

**Comment by soilnest** [comment]
It usually won't work in encrypted networks.Due to fire sheep's code it won't work on encrypted networks as far as I know... If you know hat you are doing (capture the handshake with i.e. aitcracg-ng and implement it in some other tool) you can still do the same stuff as long as its not WAP/WAP2 enterprise. Then you'd need a tool like Asleap (for CISCO LEAP) and it all start getting a bet more illegal when you force deauth to get credentials from passive monitoring and sidejacking.
Anyway, the point is I don't think firesheep will work on encrypted networks.

**Comment by nooorwala** [comment]
backend exited error1

**Comment by nooorwala** [comment]
plzzzzz someone help me firesheep is not working when i start capturing seem one error bckend exited 1 soo plz help me what i do  i need reply argently

**Comment by nooorwala** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/9681135/5005938/ccd3aa96-6a5a-11e4-91f7-52612a8a2834.png)
  plz solv me prplm
