### ISSUE TITLE
Compile under Visual Studio (Windows)

### ISSUE THREAD

**Issue by Flamefire** [codebutler/firesheep#113]
I made a version of the backend, that can be compiled under Visual Studio and so nativly for/under Windows.
I'm willing to supply the patch with a few conditional defines needed there, if you are interested. An answer would be nice

**Comment by codebutler** [comment]
This sounds interesting, I'd be happy to see your code.

**Comment by Flamefire** [comment]
Here it is: http://www.sendspace.com/file/obhiae (may need a check on OSX because of stdint.h vs defined types. I added a conditional (isdef WIN32) there and dont know if it is maybe defined under OSX too)
