### ISSUE TITLE
Invalid Interface

### ISSUE THREAD

**Issue by uknownhero** [codebutler/firesheep#12]
Every time I try to capture in Firefox 3.6.11 it says Invalid Interface. Any fix for this?

**Comment by tta013** [comment]
Having the same issue on Windows. Had put WinPcap already.

**Comment by uknownhero** [comment]
I have WinPcap installed and running on windows 7 64-bit. It will always say invalid interface for some reason.

**Comment by bk2006** [comment]
If you have Windows 7, right click on your firefox icon and click "Troubleshoot comparability". Then it will go through the process and allow you to run firefox in Windows XP SP3 mode. Running firefox in XP mode will fix the invalid interface problem. Unfortunately I now have the "backend exited with error 1" problem.

**Comment by codebutler** [comment]
If you're still having problems, please ask on the discussion group:
http://groups.google.com/group/firesheep
