### ISSUE TITLE
failed to set hardware filter to promiscuous mode

### ISSUE THREAD

**Issue by njdude** [codebutler/firesheep#120]
I have Win XP sp3 and firefox 3.16.13 and keep getting this error message: Couldn't open device \Device\NPF_{18ECC605-1543-4AA9-86C3-C4B6D8F9A547}:failed to set hardware filter to promiscuous mode.  I installed Wincap first.  I also see this error: 
Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [IMozPopenProcess.Stop] JS frame  and it points to the Mozilla\Firefox\Profiles\fd5918mk.default\extensions\firesheep@codebutler.com\modules\FiresheepSessions.js :: anonymous:: line78" data: no

**Comment by Sil3n7** [comment]
Exact same problem for me :'( Win Xp sp3 and Fierfox 3.6.13

**Comment by codebutler** [comment]
This means your wireless card isn't compatible. I'll change this to display a better error message in the next version.
