### ISSUE TITLE
Can anyone name a working adapter/OS combination

### ISSUE THREAD

**Issue by layerviii** [codebutler/firesheep#124]
Hello All,

I have reluctantly come to this forum as I am still havinng problems with this software. I have tried 3 different USB WiFi adapters but am still not getting any traffic generated.

I am currently using windows 7 (May be the problem) but will happily partiton to XP also. I also have the WN111v2. I am only getting the interfaces showing up as microsoft but no traffic is being shown.

I am using this Xpi as some research for a university project so do not mind investing in the correct hardware, but I have yet to find any that actually work.

If someone has a working combination could they please post!

Kind Regards

**Comment by layerviii** [comment]
bump

**Comment by orinxxx** [comment]
I have the same issue, I had XP, worked great, now on 7 and it's failing completely, won't even stop capturing without closing out... oh yeah, only showing Micorsoft in the Interfaces option.

When hitting Capture:
[Exception..."Component returned failure code:0x80004005(NS_ERROR_FAILURE) location:"JS frame ::///C:.....etc....Mozilla/Firefox/Profiles/xzz6fvay.default/extensions/firesheep@codebutler.com/modules.FiresheepSession.js::anonymous :: line 78" data:no]

Now won't close out....

Thanks in Advance

**Comment by codebutler** [comment]
Please use the discussion group for general questions. https://groups.google.com/forum/#!forum/firesheep
