### ISSUE TITLE
Working adapter/OS combinations

### ISSUE THREAD

**Issue by layerviii** [codebutler/firesheep#125]
I am looking for an adapter that someone has proven with this programme.

I am using Windows 7 and the WN111v2 (I know windows 7 may be the problem, and I am willing to partition to XP/7) I am also willing to buy the correct adapter (not the WinPcap one!!!!) I have tried over 3 adapters now but am still not getting any network traffic. Please can you list any working combinations.

**Comment by codebutler** [comment]
Please use the discussion group for general questions. https://groups.google.com/forum/#!forum/firesheep
