### ISSUE TITLE
Handler for Bebo

### ISSUE THREAD

**Issue by chloe99** [codebutler/firesheep#127]
```
// Authors:
// Chloe99
register({ name: 'Bebo',
url: 'http://www.bebo.com',
domains: [ 'bebo.com' ],
sessionCookieNames: [ 'Email' , 'bdaysession'],

identifyUser: function () {

var resp = this.httpGet(this.siteUrl);
this.userName = resp.body.querySelector('.user-pic img').alt;
this.userAvatar = resp.body.querySelector('.user-pic img').src;

} });
```

This works but not as smoothly as I'd like, and I want to learn so...

1) Displays users fine from Firefox but when testing by logging in with IE, it gives an error and won't display the username/avatar.
2) After clicking the capture link in Firesheep it appears to have failed, but if you then CLEAR COOKIES (it doesn't matter if you cleared before clicking, you have to clear AFTER clicking), and then re-click the link in Firesheep, it'll hijack successfully. Any idea why and how it can be fixed?

**Comment by codebutler** [comment]
Please re-open if this handler still works.
