### ISSUE TITLE
Can't Get Firesheep To Work

### ISSUE THREAD

**Issue by weezerwarrior** [codebutler/firesheep#133]
I use windows vista i downloaded the newest version of winpcap and 
firesheep i also downloaded firefox 3.6.16i opened firefox and went to 
add ons and attempted to drag firesheep into it but an x came up and 
it wouldnt allow me to move it into there so i double clicked on 
firesheep and tried to open it in firefox that way a screen came up in 
firefox that asked me if i wanted to open or save the file i tried to 
open it but a blank screen came up can someone tell me what im doing 
wrong

**Comment by ghost** [comment]
I would do it in linux with a alfa one wifi adapter... its the cheapest way I've found to do it...
The plugin that works in linux 10.04 (no ff4 support) can be found here
http://deauththis.com/forum2/?did=6
