### ISSUE TITLE
xulrunner 2.0

### ISSUE THREAD

**Issue by CounterPillow** [codebutler/firesheep#138]
Make seems to fail when FireSheep is built on ArchLinux with Xulrunner >= 2.0 installed.

<pre>
Making all in mozpopen
make[1]: Entering directory `/home/fratti/firesheep/mozpopen'
mkdir -p ../xpi/platform/Linux_x86-gcc3/components
g++ -shared -fno-rtti -fPIC MozPopenModule.cpp unix/MozPopenProcess.cpp -g -O2  -I ../mozpopen -I ../mozpopen/unix -mtune=generic -m32 -fshort-wchar -I/usr/include/xulrunner-2.0 -I/usr/include/nspr   -L/usr/lib/xulrunner-devel-2.0/lib -lxpcomglue_s -lxul -lxpcom -lplds4 -lplc4 -lnspr4 -lpthread -ldl   -o ../xpi/platform/Linux_x86-gcc3/components/MozPopen.so
MozPopenModule.cpp:24:31: schwerwiegender Fehler: nsIGenericFactory.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.
In file included from /usr/include/xulrunner-2.0/nscore.h:50:0,
                 from /usr/include/xulrunner-2.0/nsXPCOMStrings.h:42,
                 from /usr/include/xulrunner-2.0/nsStringAPI.h:53,
                 from unix/MozPopenProcess.cpp:24:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:109:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:113:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:117:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:120:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:124:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:127:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:131:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:134:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new(size_t)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:229:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:235:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:241:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:247:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:303:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-2.0/mozilla/mozalloc.h:309:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
In file included from /usr/include/xulrunner-2.0/nsStringAPI.h:56:0,
                 from unix/MozPopenProcess.cpp:24:
/usr/include/xulrunner-2.0/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Malloc(size_t)«:
/usr/include/xulrunner-2.0/nsTArray.h:84:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-2.0/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Realloc(void*, size_t)«:
/usr/include/xulrunner-2.0/nsTArray.h:88:34: Fehler: »moz_xrealloc« wurde in diesem Gültigkeitsbereich nicht definiert
make[1]: *** [../xpi/platform/Linux_x86-gcc3/components/MozPopen.so] Fehler 1
make[1]: Leaving directory `/home/fratti/firesheep/mozpopen'
make: *** [all-recursive] Fehler 1
</pre>

Here's the build log, some stuff is in german but I think it's still of use.

Thanks for answers in advance!

**Comment by CounterPillow** [comment]
nsIGenericFactory has to be replaced with mozilla/ModuleUtils.h, but it still tries to use mozalloc.h... weird

**Comment by merlin2004** [comment]
same issue here.
fedora 15 with xulrunner-2-sdk

**Comment by merlin2004** [comment]
but I used the newest version from git repo (timestamp: 2011-03-24:07:08:36)

Here my output (sorry for german language)

#####################################################################################
Making all in mozpopen
make[1]: Entering directory `/home/*********/Downloads/firesheep/mozpopen'
mkdir -p ../xpi/platform/Linux_x86-gcc3/components
g++ -shared -fno-rtti -fPIC MozPopenModule.cpp unix/MozPopenProcess.cpp -g -O2  -I ../mozpopen -I ../mozpopen/unix -mtune=generic -m32 -fshort-wchar -I/usr/include/xulrunner-sdk-2 -I/usr/include/nspr4   -L/usr/lib/xulrunner-sdk-2/lib -lxpcomglue_s -lxul -lxpcom -lplds4 -lplc4 -lnspr4 -lpthread -ldl   -o ../xpi/platform/Linux_x86-gcc3/components/MozPopen.so
In file included from /usr/include/xulrunner-sdk-2/nscore.h:50:0,
                 from /usr/include/xulrunner-sdk-2/mozilla/Module.h:41,
                 from /usr/include/xulrunner-sdk-2/mozilla/ModuleUtils.h:42,
                 from MozPopenModule.cpp:24:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:109:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:113:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:117:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:120:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:124:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:127:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:131:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:134:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:229:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:235:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:241:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:247:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:303:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:309:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
In file included from /usr/include/xulrunner-sdk-2/nsStringAPI.h:56:0,
                 from ../mozpopen/unix/MozPopenProcess.h:25,
                 from MozPopenModule.cpp:26:
/usr/include/xulrunner-sdk-2/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Malloc(size_t)«:
/usr/include/xulrunner-sdk-2/nsTArray.h:84:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Realloc(void*, size_t)«:
/usr/include/xulrunner-sdk-2/nsTArray.h:88:34: Fehler: »moz_xrealloc« wurde in diesem Gültigkeitsbereich nicht definiert
In file included from /usr/include/xulrunner-sdk-2/nscore.h:50:0,
                 from /usr/include/xulrunner-sdk-2/nsXPCOMStrings.h:42,
                 from /usr/include/xulrunner-sdk-2/nsStringAPI.h:53,
                 from unix/MozPopenProcess.cpp:24:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:109:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:113:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:117:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:120:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:124:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:127:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:131:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:134:5: Fehler: expected initializer before »NS_ATTR_MALLOC«
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:229:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:235:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:241:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const std::nothrow_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:247:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new(size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:303:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h: In Funktion »void* operator new [](size_t, const mozilla::fallible_t&)«:
/usr/include/xulrunner-sdk-2/mozilla/mozalloc.h:309:27: Fehler: »moz_malloc« wurde in diesem Gültigkeitsbereich nicht definiert
In file included from /usr/include/xulrunner-sdk-2/nsStringAPI.h:56:0,
                 from unix/MozPopenProcess.cpp:24:
/usr/include/xulrunner-sdk-2/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Malloc(size_t)«:
/usr/include/xulrunner-sdk-2/nsTArray.h:84:28: Fehler: »moz_xmalloc« wurde in diesem Gültigkeitsbereich nicht definiert
/usr/include/xulrunner-sdk-2/nsTArray.h: In statischer Elementfunktion »static void* nsTArrayInfallibleAllocator::Realloc(void*, size_t)«:
/usr/include/xulrunner-sdk-2/nsTArray.h:88:34: Fehler: »moz_xrealloc« wurde in diesem Gültigkeitsbereich nicht definiert
make[1]: *** [../xpi/platform/Linux_x86-gcc3/components/MozPopen.so] Fehler 1
make[1]: Leaving directory`/home/*****_**/Downloads/firesheep/mozpopen'
make: *_\* [all-recursive] Fehler 1
#####################################################################################

**Comment by pisto** [comment]
https://github.com/codebutler/firesheep/issues/141

**Comment by falsefifth** [comment]
keymaster, is that you?
