### ISSUE TITLE
Not compatible with firefox 5.0

### ISSUE THREAD

**Issue by wordinvestor** [codebutler/firesheep#140]
First i install Winpcap and then i install firesheep from http://codebutler.github.com/firesheep/  but firefox display error that "Not compatible with firefox 5.0". I use geniune window xp 2003 with updates till now.
Can any one help me to install firesheep in firefox 5.0

**Comment by vadamee1996** [comment]
if you go into the firesheep code [i used eclipse] and change max version to 5.0\* [ its on line 22 ]

**Comment by oliverkrystal** [comment]
The xpi is not compatible.  I've noticed a firefox 4 branch, however after merging the changes I cannot successfully build Firesheep with Xulrunner 2.0.

This "hack" doesn't really fix anything.  Perhaps your best option is to pick up the last Firefox 3.6.x availble from PortableApps.com.

**Comment by hobson** [comment]
Same here. Can't build with xulrunner 2.0 and can't install xpi successfully built from xulrunner 1.9.2 using firefox5 branch on github. Using Ubuntu 11.04.

**Comment by hobson** [comment]
Was able to get the build/install to complete using https://github.com/codebutler/firesheep/wiki/Linux-Install with xulrunner 1.9.2 and the install.rdf line 24 hack to increase the max version number. But when you launch the plugin preferences you get a blank OK/Cancel dialog that doesn't accept anything but hitting cancel, and the subsequent settings tabs/dialogs are similarly blank and unusable.
