### ISSUE TITLE
Building for firefox 5 on Ubuntu 11.04 x64, close to get it working...

### ISSUE THREAD

**Issue by pisto** [codebutler/firesheep#141]
I've put some efforts in compiling the firefox4 branch in the aforementioned environment, and there are a few blockers.
1) you need to bump up the upper version number for compatibility in install.rdf (trivial)
2) you need to add '#include <mozilla-config.h>' at the very beginning of each .cpp file of the mozpopen folder. In my opinion, headers should work by themselves and never require the programmer to include something before, but that's not what the xulrunner devs thought evidently.
3) the fix of permissions work in the standalone backend (I didn't test actual capturing, but --list-interfaces worked after --fix-permissions), but doesn't in firefox (resulting in a "Cc is not defined" error), even if I run before --fix-permission on the copy of the backend that firefox keeps in its plugin folder. Here, I'm lost, I have no idea for a fix. I suggest you to investigate the linux capabilities mechanism, a way to permanently grant to an executable the rights to do certain things that normally would require root access. I've succesfully used CAP_NET_RAW in other programs for raw socket programming, and in this case CAP_NET_ADMIN seems a good chance.

**Comment by jpiccari** [comment]
Nevermind, should've looked before I typed...

**Comment by codebutler** [comment]
See the firefox5 branch. It works on OSX, haven't started on Linux/Windows yet.

**Comment by pisto** [comment]
last commit in firefox5 branch restores full functionality of firesheep for firefox 5. Thanks, you deserve a beer.
