### ISSUE TITLE
No pcap-config on Windows

### ISSUE THREAD

**Issue by juliensobrier** [codebutler/firesheep#144]
configure.ac looks for pcap-config. But thi s file is not availabel on WIndows, even after installing Winpcap. I think the PCAP_LIBS and PCAP_FLAGS should be defined "manually" forWindows.

**Comment by athirn** [comment]
as mentioned above, configure.ac runs pcap-config to setup the variables PCAP_LIBS and PCAP_FLAGS.  If you follow the instructions at, http://mathieu.carbou.free.fr/wiki/index.php?title=Winpcap_/_Libpcap , you would set PCAP_LIBS to '-lwpcap'. For PCAP_FLAGS, try ' -I /usr/include/pcap'. BTW, edited configure.ac with these values.

**Comment by juliensobrier** [comment]
Thank you. I was able to get a bit further, but I hit another issue:

/usr/include/netinet/tcp.h:72:0: note: this is the location of the previous definition
src/tcpip.h:47:1: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:53:2: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:57:1: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:66:2: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:70:1: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:78:2: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:95:1: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:100:2: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:106:1: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:121:2: error: expected constructor, destructor, or type conversion before '(' token
src/tcpip.h:125:1: error: expected constructor, destructor, or type conversion before '(' token
make[1]: **\* [libfiresheep_la-http_sniffer.lo] Error 1
make[1]: Leaving directory `/cygdrive/c/depot/research_team/firesheep/backend'
make: **\* [all-recursive] Error 1

It looks like the compiler does not like the PACK_START / PACK_END commands
