### ISSUE TITLE
Firesheep Help: Wifi Card not appear in the Capture Screenshot

### ISSUE THREAD

**Issue by Simon80** [codebutler/firesheep#147]
Hello, I install Firesheep in the Firefox 3.0.6 but in the Preferences my wi-fi card not appear...  any suggestion??? Thanks!!!

P.S. My Screenshot: http://img233.imageshack.us/img233/9847/myscreenshot.jpg

**Comment by putradedy** [comment]
erfwwfg

**Comment by putradedy** [comment]
grsdgrr
