### ISSUE TITLE
can't build branch master (firefox7) on backtrack 5

### ISSUE THREAD

**Issue by obilodeau** [codebutler/firesheep#157]
``` shell
/bin/sh ../libtool --tag=CXX   --mode=link g++   -DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/hal -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include   -Wall -g -O0   -DPLATFORM_LINUX   -o libfiresheep.la -rpath /usr/local/lib libfiresheep_la-libfiresheep.lo libfiresheep_la-http_sniffer.lo libfiresheep_la-http_packet.lo libfiresheep_la-http_parser.lo  libfiresheep_la-linux_platform.lo -L /usr/lib -lpcap    -L/lib -lhal -ldbus-1 -lpthread -lrt   
libtool: link: require no space between `-L' and `/usr/lib'
make[1]: *** [libfiresheep.la] Error 1
make[1]: Leaving directory `/root/src/firesheep2/backend'
```

I wish I was more familiar with build tools.. Can someone point me to what file needs fixing here? What generates the wrong libtool call?

Thanks

**Comment by autocesco** [comment]
from bash history:

fgrep -r 'L /usr/lib' *
...
sed -i 's|L /usr/lib|L/usr/lib|g' config.status Makefile backend/Makefile
make

**Comment by joseluislucas** [comment]
The Same here, Autocesco I dont get what you mean. 
We are on the gates to make it work.   Backtrack 5 R1.   And when I make thats the error

make[1]: **\* [libfiresheep.la] Error 1
make[1]: Leaving directory `/root/Desktop/firesheep/firesheep/backend'
make: **\* [all-recursive] Error 1

Any solution? 
Many Thanks

**Comment by obilodeau** [comment]
I was able to build with @autocesco's suggestion. @zaikar you need to do the sed between the ./autogen.sh and the make steps.

@autocesco, any idea what change to make where so that everyone can build on linux without doing this manual search/replace?

**Comment by obilodeau** [comment]
After some research it seems that it's an upstream issue: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=567570

I'll file a ticket to backtrack so that they update their libpcap-dev version to a fixed one.

**Comment by taprootphoto** [comment]
Same problem here. I followed @autocesco advise and I got no dice. 
Just to be sure I did it right. Here are the commands I ran:
First I ran:
./autogen.sh 
(Worked perfectly Returned: Firesheep-0.1 Platform:  osx)

Then I ran:
sed -i 's|L /usr/lib|L/usr/lib|g' config.status Makefile backend/Makefile

(Returned: sed: 1: "config.status": command c expects \ followed by text)

Then I ran:
make

(Returned: Making all in backend
/bin/sh ../libtool --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"Firesheep\" -DPACKAGE_TARNAME=\"firesheep\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"Firesheep\ 0.1\" -DPACKAGE_BUGREPORT=\"eric@codebutler.com\" -DPACKAGE=\"firesheep\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BOOST=1 -DHAVE_BOOST_FORMAT_HPP=1 -DHAVE_BOOST_ALGORITHM_STRING_HPP=1 -I. -I deps/ -I deps/http-parser -I deps/json_spirit    -Wall -g -O0 -DPLATFORM_OSX -arch i386 -arch x86_64   -MT libfiresheep_la-libfiresheep.lo -MD -MP -MF .deps/libfiresheep_la-libfiresheep.Tpo -c -o libfiresheep_la-libfiresheep.lo `test -f 'src/libfiresheep.cpp' || echo './'`src/libfiresheep.cpp
libtool: compile:  g++ -DPACKAGE_NAME=\"Firesheep\" -DPACKAGE_TARNAME=\"firesheep\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"Firesheep 0.1\"" -DPACKAGE_BUGREPORT=\"eric@codebutler.com\" -DPACKAGE=\"firesheep\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BOOST=1 -DHAVE_BOOST_FORMAT_HPP=1 -DHAVE_BOOST_ALGORITHM_STRING_HPP=1 -I. -I deps/ -I deps/http-parser -I deps/json_spirit -Wall -g -O0 -DPLATFORM_OSX -arch i386 -arch x86_64 -MT libfiresheep_la-libfiresheep.lo -MD -MP -MF .deps/libfiresheep_la-libfiresheep.Tpo -c src/libfiresheep.cpp  -fno-common -DPIC -o .libs/libfiresheep_la-libfiresheep.o
g++-4.2: -E, -S, -save-temps and -M options are not allowed with multiple -arch flags
make[1]: **\* [libfiresheep_la-libfiresheep.lo] Error 1
make: **\* [all-recursive] Error 1)

I've been working on this for about 6 hours now and I know I am SO close. Somebody please push me back to sanity so I finally go to bed and get some rest. Man, Firesheep kicked my @ss today.

**Comment by taprootphoto** [comment]
Well I finally found a temporary solution. I stumbled on this link where you just download the .xpi file and drag it over to your firefox addons and install it that way. After restarting firefox and viewing Firesheep in sidebar, I was prompted to input my password. Then the magic began again. Clicked on start capture with no errors. Logged into Tumblr on my iPhone and sure as hell it popped right up and I was able to double click an sidejack my Tumblr account. Anyway here's the link. I hope this saves somebody a lot of wasted time. 

https://github.com/codebutler/firesheep/downloads

**Comment by philcolbourn** [comment]
Sill an issue under Ubuntu Lucid 10.04.

Blindly installed following packages:

libpcap-dev
xulrunner-1.9.2-dev
libboost-all-dev
libtool
libhal-dev
autoconf
libudev-dev

Got space-after-L error.

/bin/bash ../libtool --tag=CXX   --mode=link g++    -Wall -g -O0   -DPLATFORM_LINUX   -o libfiresheep.la -rpath /usr/local/lib libfiresheep_la-libfiresheep.lo libfiresheep_la-http_sniffer.lo libfiresheep_la-http_packet.lo libfiresheep_la-http_parser.lo  libfiresheep_la-linux_platform.lo -L /usr/lib -lpcap    -ludev  
libtool: link: require no space between `-L' and`/usr/lib'
make[1]: **\* [libfiresheep.la] Error 1
make[1]: Leaving directory `/home/phil/Downloads/firesheep/backend'
make: **\* [all-recursive] Error 1

I manually edited Makefile and removed space after '-L'

> PCAP_LIBS = -L /usr/lib -lpcap

Then it stopped again.

Making all in backend
make[1]: Entering directory `/home/phil/Downloads/firesheep/backend'
/bin/bash ../libtool --tag=CXX   --mode=link g++    -Wall -g -O0   -DPLATFORM_LINUX   -o libfiresheep.la -rpath /usr/local/lib libfiresheep_la-libfiresheep.lo libfiresheep_la-http_sniffer.lo libfiresheep_la-http_packet.lo libfiresheep_la-http_parser.lo  libfiresheep_la-linux_platform.lo -L /usr/lib -lpcap    -ludev   
libtool: link: require no space between`-L' and `/usr/lib'
make[1]: *** [libfiresheep.la] Error 1
make[1]: Leaving directory`/home/phil/Downloads/firesheep/backend'
make: **\* [all-recursive] Error 1

I manually edited backend/Makefile and removed space after '-L'

> PCAP_LIBS = -L /usr/lib -lpcap

Compiled fine and installed to Firefox 20.
