### ISSUE TITLE
Javascript error, when open Preferences

### ISSUE THREAD

**Issue by joseluislucas** [codebutler/firesheep#158]
I get that msg when I try to Start Capturing or when I open preferences.

[Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.copyTo]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://firesheep/Firesheep.js :: <TOP_LEVEL> :: line 168"  data: no]

Any solutions...

Many Thanks

**Comment by ghost** [comment]
I get the same error. I spent some time researching this but came up with nothing. Does anyone know why this is happening?

**Comment by khalilfazal** [comment]
This bug is getting old, I have the same issue.

**Comment by peponi** [comment]
Dear Khalil Fazal,

The email sent to mail@peponi.tk with subject
"Re: [firesheep] Javascript error, when open Preferences (#158)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to mail@peponi.tk, you will not receive a delivery
notification again.

TK MAILIAS

---

Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
