### ISSUE TITLE
tries to use wrong device, always tries to use "en1"

### ISSUE THREAD

**Issue by dino7777** [codebutler/firesheep#16]
Its seems to me as if firesheep always tries to use the device
"en1".
As my wifi device is configured o be "en3", when starting capturing I get a error message:
"Couldn't get netmask for device en1: 
SIOCGIFADDR:en1:
Device not configured"

Will try to manually configure wifi device via "prefs.js" and report

**Comment by codebutler** [comment]
The interface can be changed in the Firesheep preferences.
