### ISSUE TITLE
building on 10.6.7 (libfiresheep_la-libfiresheep.lo)

### ISSUE THREAD

**Issue by ro0mquy** [codebutler/firesheep#161]
every time i start MAKE, i got this error message:

```
g++-4.2: -E, -S, -save-temps and -M options are not allowed with multiple -arch flags
make[1]: *** [libfiresheep_la-libfiresheep.lo] Error 1
make: *** [all-recursive] Error 1
```

thanks

**Comment by SBUS-CL** [comment]
I'm having exactly the same problem (OSX 10.6.8).

Also, during the autogen.sh this comes up a few times:

configure.ac:41: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
/var/tmp/autoconf/autoconf-15~193/SRC/autoconf/lib/autoconf/general.m4:1744: AC_CANONICAL_TARGET is expanded from...
configure.ac:41: the top level

Any ideas?!?!?!?!?!

**Comment by kcmani** [comment]
Same thing is happening to me as well on OSX 10.6.8.

g++-4.2: -E, -S, -save-temps and -M options are not allowed with multiple -arch flags
make[1]: **\* [libfiresheep_la-libfiresheep.lo] Error 1
make: **\* [all-recursive] Error 1

**Comment by taprootphoto** [comment]
6 hours into trying to compile the .xpi and I'm having the same issue. I'm SO CLOSE!!!!!! AHHHH!!! Man, the first time I ever used Firesheep I installed it straight from Firefox Addons. I wish that were still an option. This is crazy. I'm definitely not a command line programmer. PLEASE, I beg would someone help. I don't want to feel like I wasted my life away today. Thanks in advance.

**Comment by stefek99** [comment]
Max OS 10.6.8

```
make all > Log
g++-4.2: -E, -S, -save-temps and -M options are not allowed with multiple -arch flags
make[1]: *** [libfiresheep_la-libfiresheep.lo] Error 1
make: *** [all-recursive] Error 1
```

Log: http://pastebin.com/eZjBaBiL

---

Any hints, suggestions?

(I also tried on Mac OS 10.7.3 but again [no success](https://github.com/codebutler/firesheep/issues/169))
