### ISSUE TITLE
Support Firefox 8

### ISSUE THREAD

**Issue by Rudloff** [codebutler/firesheep#162]
I have built Firesheep on Ubuntu 11.10 but can't use it on Firefox 8.
I have edited install.rdf but I get this error when opening the preferences :
Failed to list network devices.

**Comment by Rudloff** [comment]
Running the backend manually from commandline seems to work, so is there a way to manually specify the interface in Firesheep ?

**Comment by Rudloff** [comment]
I have reinstall HAL and now it works so it seems the only thing that prevents it from working on Firefox 8 is the version number in install.rdf.

**Comment by Rudloff** [comment]
Hum, in fact there is one little problem : login does not work.

**Comment by zkhalapyan** [comment]
For future reference, running `sudo apt-get install hal` on Ubuntu 12.04.1 LTS (using Firefox 15.0.1) to fixed this issue. But again, as mentioned by @Rudloff the backend did no start correctly.
