### ISSUE TITLE
http-parser/http_parser.h' file not found

### ISSUE THREAD

**Issue by laxman01** [codebutler/firesheep#163]
when i run 'make' i get this error message 

rc/http_packet.hpp:31:10: fatal error: 'http-parser/http_parser.h' file not found
# include "http-parser/http_parser.h"

```
     ^
```

1 error generated.
make[1]: **\* [libfiresheep_la-http_sniffer.lo] Error 1
make: **\* [all-recursive] Error 1

please help me

**Comment by laxman01** [comment]
okay i have figured this problem out but when i start to capture it does not capture anything. any ideas what is happening?

**Comment by ghost** [comment]
Hi Laxman how did you solve the file not found error?

**Comment by laxman01** [comment]
download http-parser https://github.com/joyent/http-parser/zipball/master 
then go into firesheep folder then into the backend folder then copy the files downloaded into the http-parser folder in backed

**Comment by kangsterizer** [comment]
git submodule update --init (don't need to download manually) is the proper "fix"

**Comment by kensaggy** [comment]
+1 for @kangsterizer.
http-parser is configured in .gitmodules,  no need to manually download it

**Comment by gumacahin** [comment]
Forgot that step too. Thanks kangsterizer.
