### ISSUE TITLE
Build Problem - 'sys/types.h' file not found

### ISSUE THREAD

**Issue by stefek99** [codebutler/firesheep#169]
Have problems with build, any ideas where to find this file / which library to install?

**make**
Making all in backend
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DPACKAGE_NAME=\"Firesheep\" -DPACKAGE_TARNAME=\"firesheep\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"Firesheep\ 0.1\" -DPACKAGE_BUGREPORT=\"eric@codebutler.com\" -DPACKAGE_URL=\"http://codebutler.github.com/firesheep\" -DPACKAGE=\"firesheep\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BOOST=1 -DHAVE_BOOST_FORMAT_HPP=1 -DHAVE_BOOST_ALGORITHM_STRING_HPP=1 -I. -I deps/ -I deps/http-parser -I deps/json_spirit    -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -Wall -g -O0 -DPLATFORM_OSX -arch i386 -arch x86_64   -MT libfiresheep_la-http_parser.lo -MD -MP -MF .deps/libfiresheep_la-http_parser.Tpo -c -o libfiresheep_la-http_parser.lo `test -f 'deps/http-parser/http_parser.c' || echo './'`deps/http-parser/http_parser.c
libtool: compile:  clang -DPACKAGE_NAME=\"Firesheep\" -DPACKAGE_TARNAME=\"firesheep\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"Firesheep 0.1\"" -DPACKAGE_BUGREPORT=\"eric@codebutler.com\" -DPACKAGE_URL=\"http://codebutler.github.com/firesheep\" -DPACKAGE=\"firesheep\" -DVERSION=\"0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_BOOST=1 -DHAVE_BOOST_FORMAT_HPP=1 -DHAVE_BOOST_ALGORITHM_STRING_HPP=1 -I. -I deps/ -I deps/http-parser -I deps/json_spirit -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -Wall -g -O0 -DPLATFORM_OSX -arch i386 -arch x86_64 -MT libfiresheep_la-http_parser.lo -MD -MP -MF .deps/libfiresheep_la-http_parser.Tpo -c deps/http-parser/http_parser.c  -fno-common -DPIC -o .libs/libfiresheep_la-http_parser.o
In file included from deps/http-parser/http_parser.c:21:
deps/http-parser/http_parser.h:28:10: fatal error: 'sys/types.h' file not found
# include <sys/types.h>

```
     ^
```

1 error generated.
make[1]: **\* [libfiresheep_la-http_parser.lo] Error 1
make: **\* [all-recursive] Error 1

**gcc --version**
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)

**/usr/bin/sw_vers**
ProductName:    Mac OS X
ProductVersion: 10.7.3
BuildVersion:   11D2001

**Comment by PatrickTulskie** [comment]
Did you ever resolve this?  I think it has something to do with a messed up XCode installation but I am not sure what actually needs to be fixed.

**Comment by stefek99** [comment]
Tried asking Clang experts: http://lists.cs.uiuc.edu/pipermail/cfe-dev/2012-May/021152.html

(thanks for reminding)

**Comment by PatrickTulskie** [comment]
I just got it to build...

In the makefile, the CFLAGS variable was set incorrectly.  It should be:

CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7 $(CXXFLAGS)

That's for my system though since I have the newest XCode installed.  I'm not sure how to fix this so that it works correctly with autogen though.  At least Firesheep builds correctly and captures under Firefox 13 now.

**Comment by stefek99** [comment]
Still getting error:

```
In file included from deps/http-parser/http_parser.c:21:
deps/http-parser/http_parser.h:28:10: fatal error: 'sys/types.h' file not found
```

Full output: http://pastebin.com/fa2AGjrC

**Comment by PatrickTulskie** [comment]
Did you double check that you have that SDK in that directory?  Yours might be different.

Also, try doing a `make clean` and then doing `make` again.

**Comment by stefek99** [comment]
```
ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.6.sdk  MacOSX10.7.sdk
```

```
make clean
```

It removed some stuff.

`make all > LOG`
It took some time to compile, I was hoping this is it... Not really.
Log: http://pastebin.com/mM3CYuN4
Error stream:

```
In file included from deps/http-parser/http_parser.c:21:
deps/http-parser/http_parser.h:28:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^
1 error generated.
make[1]: *** [libfiresheep_la-http_parser.lo] Error 1
make: *** [all-recursive] Error 1
```

It seems to me like all the time same error. Maybe I should install C compiler other than Xcode?

**Comment by PatrickTulskie** [comment]
I'm not sure.  I guess my problem was different than your problem is.  You installed boost, right?  Initialized the git submodules?  I'm not really sure what else would be wrong.

I didn't do `make all` though... I just did `make`.

**Comment by gtangil** [comment]
Same problem here.

Any other thought on this?

**Comment by giblfiz** [comment]
I was having no luck changing the Makefile (for reasons I totally don't understand) 
But when I tried changing the CFLAGS def in configure.ac
to
CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7

it worked like a charm. 

I also mailed off a patch, so hopefully that will get rolled in.

**Comment by AlamiMejjati** [comment]
@giblfiz @stefek99  Where can i found configure.ac ? i don't really find it. I'm having the same problem as stefek, i'm using XCODE 5.2 on OSX Yosemite

**Comment by supan** [comment]
If you are of Mavericks or above, try running this command
"xcode-select --install" before doing make.

**Comment by jwcrandall** [comment]
For Mojave
softwareupdate --install -a
