### ISSUE TITLE
backend exited with error 1.

### ISSUE THREAD

**Issue by gunasekhar12** [codebutler/firesheep#171]
when im trying to capture....its not showing any sites available for capturing....and when i stop capturing, its showing "backend exited with error 1.".what do i do now...?

**Comment by zkhalapyan** [comment]
From firesheep/backend run `sudo ./backend --fix-permissions` and then restart firefox. Worked for me on a similar issue.

**Comment by jampeleven** [comment]
How do I do this suggestion? -From firesheep/backend run sudo ./backend --fix-permissions and then restart firefox. Worked for me on a similar issue.

**Comment by zkhalapyan** [comment]
What's not clear?
