### ISSUE TITLE
Building with Windows not working

### ISSUE THREAD

**Issue by mertsakarya** [codebutler/firesheep#177]
When I try to run 

autoreconf --force --install --verbose .

I get error 

checking for pcap-config... no
configure: error: pcap-config not found (libpcap not installed ?)

I got VS2010,  Cygwin, WinPcap, and boost installed on Windows 7

How can I create an XPI for windows that supports Firefox 15

**Comment by guillermart** [comment]
Got the same error message, any suggestion?
