### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by clinton4** [codebutler/firesheep#18]
Can anybody tell me how to install this on a Win XP computer? I cant find any info on that... Arghh..!

**Comment by TrevorReznik** [comment]
First you have ton dowload firesheep extension here : http://github.com/codebutler/firesheep/downloads
Then in firefox click on "File" and open a file. Select firesheep and click next :)
Firesheep will be installed.

**Comment by ilovesurfing** [comment]
install winPcap, then after installing, download the firesheep extension at

http://github.com/codebutler/firesheep/downloads

save it somewhere where you will remember. Then go to where it was downloaded, right click and open with firefox. The firefox extension addon window will show, click install, and then it will have you restart firefox. Then it is installed. After that, open up firefox, click view, go to sidebar, and click firesheep. you will then have a window on the left side of firefox that says firesheep and start capturing. 

There you go! Hope this helped

**Comment by TrevorReznik** [comment]
Your tuto is better than mine :)

**Comment by ilovesurfing** [comment]
:D

**Comment by ilovesurfing** [comment]
im having the backend exited with error 1 message though :(

no hacking teh facebook today unfortunately :(

**Comment by nodoubt** [comment]
ok what file do i need to 'open up'? do you right click the zip file or the install.rdf file or ....?

**Comment by SWiT** [comment]
open the .xpi file with firefox.

**Comment by nodoubt** [comment]
can't find any .xpi file.....

**Comment by SWiT** [comment]
then you didn't download the right thing. http://github.com/downloads/codebutler/firesheep/firesheep-0.1-1.xpi  Maybe you grabbed the source files.

**Comment by nodoubt** [comment]
i downloaded that. it turned into a zip file. i unzipped it and found a few folders, an install.rdf, and chrome.manifesto file. no .xpi file

**Comment by SWiT** [comment]
@nodoubt "i downloaded that. it turned into a zip file" that seems very odd to me.  Try renaming the file to "firesheep-0.1-1.xpi".  What OS are you running?  If it's windows make sure you turn off "Hide extensions of known file types".

**Comment by ilovesurfing** [comment]
why are you turning it into a zip file? The .xpi file is the filename for a firefox extension...  just leave it how it is and open it with firefox

**Comment by nodoubt** [comment]
i dont turn it into a zip file....it automatically turns into one :) it's Windows Vista. Thanks for all of your help!

**Comment by ilovesurfing** [comment]
hmm I dont think that it should turn into a zip file... regardless, try right clicking the "zip file" and opening up with firefox. You shouldnt have to extract anything to get this to work. Does it have the file extension .xpi? Because that is how it should download when you get it from   http://github.com/codebutler/firesheep/downloads

**Comment by ilovesurfing** [comment]
here is the direct link...

http://github.com/downloads/codebutler/firesheep/firesheep-0.1-1.xpi

**Comment by SWiT** [comment]
@nodoubt Good luck with Windows Vista.  I couldn't get it to work on my Vista laptop over the lunch hour.  I think you must have a "zip" program associated with the xpi file type or some antivirus is being overly zealous with your downloaded file types.  From Firefox click File->Open File... then navigate to the file you downloaded.  Rename the file to something.xpi if you need to.

**Comment by nodoubt** [comment]
it was IE ...u can only download it on chrome or ff. thanks!!!!

**Comment by clinton4** [comment]
http://www.youtube.com/watch?v=uXDmivKmA6M

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
