### ISSUE TITLE
[Feature] Hyves handler

### ISSUE THREAD

**Issue by meghuizen** [codebutler/firesheep#19]
```
// Firesheep script for Hyves
// by Jaco & Michiel
// http://www.hyves.nl

register({
    name: "Hyves",
    url: 'http://www.hyves.nl/',
    domains: [ 'hyves.nl' ],
    sessionCookieNames: [ 'CPR', 'GP', 'LC', 'PHPSESSID', 'SC', 'chatInitialPresence', 'realstatId' ],
    identifyUser: function () {
        var resp = this.httpGet(this.siteUrl);
        this.userName = resp.body.querySelector('#usr-optns .avatar-link').title;
        this.userAvatar = resp.body.querySelector('#usr-optns .avatar-img').src;
    }
});
```

**Comment by meghuizen** [comment]
Oh and it does not always cleanup it's session when logging off. As well as twitter.

**Comment by jelmerkoppelmans** [comment]
It doesn't work for me. It just loads the normal hyves page, not logged in or showing username or password

**Comment by raoulteeuwen** [comment]
Same as with JelmerTheBest: the Hyves session of another user on the unprotected network shows up in the Firesheep window, but clicking it, doesn't make you being logged in as that user; if you're logged into Hyves yourself, you get your own page. If you're not logged in, the Hyves homepage is shown, so not being logged in as that user.

As a noob, i've tried to study what cookies Hyves creates, both during visting the public website, as well as when logging in. secure.hyves.org is a domain popping up. I've tried to add that url, and the cookie-names that are created under that domain (like auth_t) , but i only seem to be able to break the code: no Hyves logins shows up in the firesheep window after i edit the code.

**Comment by codebutler** [comment]
Please re-open if this handler still works.
