### ISSUE TITLE
"open wifi" NAT vs. Internet facing IP

### ISSUE THREAD

**Issue by SWiT** [codebutler/firesheep#21]
I think I know why I can't get firesheep to capture on our campus' open wifi.  All of our wifi IPs are "internet facing" but firewalled to hell (basically no ports are open by default).  This means the attacker and victim wouldn't normally share an IP.  Versus a NAT were both people share the internet IP  and have local LAN IPs (192.168.1.100 etc.).

Am I correct or full of ignorance?

If this is not the issue then for the record I'm running OSX 10.6.4 on a new mac mini and FF3.6.11.  Firesheep captures nothing but my local machines facebook traffic.

**Comment by colbywg** [comment]
I had the same issue with my university wifi, but I'm a total amateur. I do know that my school uses a WPA2 network, which (in my limited knowledge), sounds like what your school uses.

**Comment by SWiT** [comment]
My campus uses "open" wifi with no encryption key.  WPA2 is a newer encryption method that is supposed to encrypt all the users in a way that they can not see each others traffic.  My question to the group is do the attacker and victim both need to be behind a NAT/Router/Firewall (one shared internet facing IP) or can they both have different internet facing IPs.  Does Firesheep only display "highjackable" sessions or any session data it sees?

**Comment by SWiT** [comment]
As a follow up:  I got the Mac mini working on a open wifi network I setup.  So I captured no sessions from the campus wifi that issues a internet facing IP to each user.  With the same hardware connected to a open wireless router with a firewall (NAT) I could capture sessions.  It did take about 5 minutes of facebooking before it did capture the session so BE PATIENT!
