### ISSUE TITLE
Firesheep not compatable with OSX/PowerPC (PPC)

### ISSUE THREAD

**Issue by Nusmata** [codebutler/firesheep#26]
The message I get:
'Incompatible Extension
"Firesheep" could not be installed because it is not compatible with your Firefox build type (Darwin_ppc=gcc3). Please contact the author of this item about the problem.'

Hello authors? It's just an old PowerBook G4 with OS 10.4.11 but I would like to know who's phishin'

**Comment by codebutler** [comment]
Hi,

At this time, Firesheep is not supported on PowerPC systems.
