### ISSUE TITLE
wifi chipsets and OS

### ISSUE THREAD

**Issue by SWiT** [codebutler/firesheep#27]
Can people who have Firesheep working correctly please post what wifi card, chipset, driver, and OS they are using.  I have a broadcom 43xx in Vista and have had no luck.  My mac mini at work is brand new and I have not figured out what chipset it uses yet.

**Comment by SWiT** [comment]
... and the mac mini does not work either.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
