### ISSUE TITLE
Still Having issues with Windows

### ISSUE THREAD

**Issue by theisovist** [codebutler/firesheep#28]
Trying to get this to work.  I've tried the different interface options, and the only sessions i can catch are my own.  The network is open, and we've tested many of the sites that you've listed.  windows vista, 32 bit.  firefox 3.6.11.  

One suggestion - I'd love to have an apply button.  I;m never sure that changing the interface actually works.  Also, do i need to stop and start capturing between interface changes?

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:
http://groups.google.com/group/firesheep

Please open a new issue for your "apply" button suggestion.

Thanks for your interest in Firesheep!
