### ISSUE TITLE
Firesheep not compatable with Mac OS X 10.4

### ISSUE THREAD

**Issue by phabeon** [codebutler/firesheep#29]
Greetings all..

I have Firesheep installed but whenever I try to capture it crashes Firefox and it then asks me to report this to mozilla...

I have been at this for 2 hours now.... read this entire page here and the guys personal one as well...

I am not seeing my issue anywhere even on a google search...

i have the original macbook pro( first edition of the mac's running intel chips)  runnning OS X 10.4.11

I am running FF 3.6.11

I have uninstalled firefox COMPLETELY and then re installed it several times.. I even googled removing FF to make sure I wasn' missin anything.. so yes even deleted those mozilla files under users/library/admin....

I still can't get Firesheep to run..  as soon as I click on it in the sidebar, i.e. capture.. it crashes...

if I go to add on's and then click on preferences for Firesheep thru the add on window, FF crashes..

Is my original Macbook Pro the culprit or am I missing something?

AnY and all help is greatly appreciated!!

thanks again!!

email:

phabeon@hotmail.com

oNe

**Comment by phabeon** [comment]
this is what FF shows me.... sorry forgot to include above..

Add-ons: firesheep@codebutler.com:0.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.11
BuildID: 20101012104758
CrashTime: 1288142299
EMCheckCompatibility: true
FramePoisonBase: 00000000f0dea000
FramePoisonSize: 4096
InstallTime: 1288127655
ProductName: Firefox
ReleaseChannel: release
SecondsSinceLastCrash: 1626
StartupTime: 1288142287
Theme: classic/1.0
Throttleable: 1
URL: http://rapidshare.com/checkfiles.html
Vendor: Mozilla
Version: 3.6.11

This report also contains technical information about the state of the application when it crashed.

**Comment by giveortake20percent** [comment]
Seconded.

**Comment by notluke** [comment]
i'm having the same problem

**Comment by ftruzzi** [comment]
same here. it looks like it doesn't work on 10.4.

It has been compiled on 10.5 so there are some library linking problems on tiger.

this is what i get in the terminal while running firesheep

macbook:~ Patrizia$ /Applications/Firefox.app/Contents/MacOS/firefox-bin
dyld: lazy symbol binding failed: Symbol not found: _fcntl$UNIX2003
  Referenced from: /Users/Patrizia/Library/Application Support/Firefox/Profiles/wwoi450c.default/extensions/firesheep@codebutler.com/platform/Darwin_x86-gcc3/components/MozPopen.dylib
  Expected in: /usr/lib/libSystem.B.dylib
