### ISSUE TITLE
Does not work on Firefox 4b6

### ISSUE THREAD

**Issue by pedrovanzella** [codebutler/firesheep#3]
TypeError: Cc['@mozilla.org/extensions/manager;1'] is undefined
is thrown and the preferance panes are blank.

**Comment by rjchicago** [comment]
I get the same issue for FF version 3.6.11

**Comment by bgenzoli** [comment]
Getting the same thing...doesn't look like it's capturing data. Also gives 'Backend exited with error 1.' message when you click Stop capturing.

**Comment by ghost** [comment]
Won't even load in 3.6. Next.

**Comment by Graurk** [comment]
Same as bgenzoli, however i am getting my data just no other data... does it have something to do with the filter?

**Comment by mvuksano** [comment]
Won't even start on my machine. I use FF 3.6.11 on Win7 32bit.

**Comment by Graurk** [comment]
@markovuksanovic I had that problem too, also running 7 32bit, and had to down grade FF to 3.6.10 to get it to work at all....

**Comment by gravedecision** [comment]
Have you all installed WinPcap first?

http://www.winpcap.org/install/default.htm

**Comment by ghost** [comment]
How do you install WinPcap on OS X?

**Comment by gravedecision** [comment]
You don't need Winpcap on OS X - it's only for Windows since it doesn't have libpcap or whatever.

**Comment by ghost** [comment]
So your question was a little irrelevant.

**Comment by gregcarlin** [comment]
I have 3.6.11 on Mac OS X and it doesn't load for me either

**Comment by gregcarlin** [comment]
I also just got version 4 beta 6 and it doesn't load for me either

**Comment by Josh61** [comment]
ive got WinPcap as well and it still doesnt work

**Comment by gregcarlin** [comment]
I dunno about 4 but for 3.6.11 GO TO VIEW>SIDEBAR>FIRESHEEP

**Comment by raybrownco** [comment]
Hey all,  I tried a few different versions of Firefox, but eventually got this to work in FF3.5.14.  You could probably get it to work in other versions as well. The trick is to open "about:config" to add a boolean preference for "extensions.checkCompatibility" and set it to "false" before trying to install the extension.  More info on this here: http://jkontherun.com/2008/06/05/how-to-force-fi/.  Oh, and of course, proceed at your own risk.

**Comment by gravedecision** [comment]
You can also edit the actual install.rdf file inside the xpi file using 7zip. I increased the max version and it worked fine.

**Comment by andig** [comment]
Same issue here. Installed om 4b6 with extension compatibility checking disabled. Following errors are thrown when opening the sidebar:

Error: Cc['@mozilla.org/extensions/manager;1'] is undefined
Source File: resource://firesheep/Firesheep.js
Line: 188
Error: uncaught exception: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://firesheep/content/ff-sidebar.js :: <TOP_LEVEL> :: line 23"  data: no]
Error: Cc is not defined
Source File: chrome://firesheep/content/ff-overlay.js
Line: 31

**Comment by andig** [comment]
Regarding the first bug some hints can be found here: http://forums.mozillazine.org/viewtopic.php?f=23&t=1875945

Similar error was fixed for GreaseMonkey like this in FF4:

```
    /*var extMan = Components.classes["@mozilla.org/extensions/manager;1"]
      .getService(Components.interfaces.nsIExtensionManager);
    var item = extMan.getItemForID(GM_GUID);
    GM_prefRoot.setValue("version", item.version);*/
    Components.utils.import("resource://gre/modules/AddonManager.jsm");

    AddonManager.getAddonByID("{e4a8a97b-f2ed-450b-b12d-ee082ba24781}", function(addon) {
       GM_prefRoot.setValue("version", addon.version)
    });
```

**Comment by andig** [comment]
Also check this: https://developer.mozilla.org/en/Addons/Add-on_Manager/Code_Samples

**Comment by pedrovanzella** [comment]
To everyone who sugested changing the addon compatibility options:
it is not the case that the addon won't install. It install fine by doing any of those tricks, it just does not RUN.

**Comment by madgrad2002** [comment]
For those of you having problems with the ReferenceError, you might want to look into your firewall.  I don't know enough about the problem to help, but I had the same issue with Comodo.  I removed the firewall and everything worked.  Then I reinstalled it (after everything was verified) and it continued to work.

**Comment by rdwilson** [comment]
I too am getting an exception error in FF 3.9.11 (NS_ERROR_FAILURE). OS is XP SP3 on a Panasonic CF-29. My capture device is a CASE AirPcap and works fine in Cain, airodump, and Wireshark but not in Firesheep...

The capture device is reported to be "not found".

**Comment by orinxxx** [comment]
I was so excited to play with Firesheep I did not read thoroughly and did not install winPcap and was getting this error in Firfox 3.6.12 WinXP SP3. I then realized the error of my ways and installed winPcap 4.1.2 and also uninstalled/reinstalled Firesheep-->success, as @codebutler mentions it is a harmless message once installed correctly.

**Comment by rdwilson** [comment]
Yes, the prerequisites are that you load WinPcap and that your wireless adapter is able to go into promiscuous mode.

Further research into my issue seems to be that Firesheep is not recognizing the adapter and throwing an exception as a result. This is odd because the adapter works in three other applications using WinPcap and shows up working correctly in Device Manager as "AirPcap Tx USB Wireless Capture Adapter". 

No big deal, really, AirPcap and Wireshark have been able to do this for years. Just wanted to experiment. BTW, great name, "Firesheep". That's baaahad.

**Comment by nooorwala** [comment]
helo plzzz fix this issue  fireshep caputring but some error google and facebook page not open
