### ISSUE TITLE
How do i install on a mac

### ISSUE THREAD

**Issue by popmad9** [codebutler/firesheep#32]
I keep clicking install.rdf and it just opens a text document in firefox....then it just stops.

**Comment by trel** [comment]
drag the .xpi from your Downloads folder back onto an open Firefox window.

**Comment by SWiT** [comment]
you may want to run firefox as root when you install it.
From the terminal type: 
sudo /Applications/Firefox.app/Contents/MacOS/firefox-bin

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
