### ISSUE TITLE
Doesn't recognize interfaces

### ISSUE THREAD

**Issue by taimur38** [codebutler/firesheep#34]
Windows 7,
Intel(R) 82577LC Gigabit Network Connection
Intel(R) Centrino(R) Advanced-N 6200 AGN
Microsoft Virtual WiFi Miniport Adapter

Firesheep doesn't recognize any interfaces on my machine. Hope this is all relevant data..

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
