### ISSUE TITLE
Firesheep on Windows 7

### ISSUE THREAD

**Issue by partridge** [codebutler/firesheep#36]
# New Thread: http://github.com/codebutler/firesheep/issues/issue/49/

**Comment by ilovesurfing** [comment]
Cain and able is coming up as malware from AVG. Has anyone had experience with this program before?

**Comment by devilwarier9** [comment]
windows thought it was bad too, but i scanned with avast and it came up clean, but it does not work for me.  It says it works with ethernet only for some reason and when I search on wifi I get the router but nothing else.  Wierd

edit: its working now, no idea why, but it is

**Comment by ZoliQua** [comment]
On Win7 it dosesn't working. And I don't understand how to use this Cain software.

**Comment by devilwarier9** [comment]
watch the video he posted, he makes it very simple, I got it working in under 5 minutes

**Comment by Richardbt71** [comment]
@ilovesurfing - Cain is a hacker tool.   You will find most hacker tools will come up as malware.  When dealing with hacker tools, download from the author's website.

**Comment by farhanmansoor** [comment]
It worked. Thanks.. I tried it on Win7 Enterprise.

**Comment by ilovesurfing** [comment]
@Richardbt71 - yeah I figured as much. As for using Cain... I am on a college campus at the moment and I am not quite sure how to deal with IP addresses that arent static. There are like a MILLION to choose from, but I guess I could just add all of them? 

Oh, and does someone want to explain what "poisoning" the network means?

**Comment by gembong** [comment]
still can't work T,T

do you guys know how the tc port number for XP?
