### ISSUE TITLE
Only sniffing my own computer/limited interface

### ISSUE THREAD

**Issue by devilwarier9** [codebutler/firesheep#37]
I recently installed firesheep and am really interested in using it, but it does not seem to be working for me.  I am on an open network, and I know there is heavy traffic (its a school), but firesheep will not show anything.  I am using Windows 7 x64, and have tried both running as admin and compatability mode to XP, but nothing works.  I installed Winpcap like it said too.  I heard somewhere you might have to change the interface, but I have tried all the options to no avail (my options were "Microsoft" and my Ethernet card - a Broadcam Netlink Gigabit Ethernet).  It will; however, sniff my own computer, both in Firefox and in IE, on either setting.  Is this just my computer? Or is this a common issue?  I feel like there should be a third option for my wireless card (an Intel Centrino Advanced-N 6200 AGN), but after restarting both Windows and my browser one did not show up.  Is it possible I have an incompatible wireless card? Or is the "Microsoft" option my wireless card? Any help is appreciated.  Thanks

**Comment by Graurk** [comment]
I have the same problems, my card being an Intel(R) 82577LM Gigabit, however I have two "Microsoft"s and by using Wireshark was able to figure out which one to use, but still only capturing the local computer.

**Comment by Maximus9** [comment]
Mine does not even show local cookies :(

**Comment by devilwarier9** [comment]
I'm thinking its not the network card, I think there's a win7 problem. I tried this and it worked, might work for ou too http://github.com/codebutler/firesheep/issues#issue/36

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
