### ISSUE TITLE
How to install in linux debian?

### ISSUE THREAD

**Issue by ghost** [codebutler/firesheep#39]
I can't seem to find the ./configure file to be able to make and make install it. Anyone know how to install it in debian ?

**Comment by Jackovson** [comment]
sh autogen.sh seems to do the job ;)

**Comment by jeremysalwen** [comment]
You need to use the linux fork anyway..  see http://github.com/michajlo/firesheep

**Comment by ghost** [comment]
I used the linux fork and the sh autogen.sh generated the configure. But now when I want to do make I receive the following error:
make[1]: Entering directory `/home/ikke/Desktop/downloads/michajlo-firesheep-cc98db4/backend'
make[1]: *** No rule to make target`deps/http-parser/http_parser.c', needed by `../xpi/platform/Linux_x86_64-gcc3/firesheep-backend'.  Stop.
make[1]: Leaving directory`/home/ikke/Desktop/downloads/michajlo-firesheep-cc98db4/backend'
make: **\* [all-recursive] Error 1

It does say x86_64-gcc3 but I am using a 32bit. So do I need to find a 32bit compatible file ?

**Comment by Ierixon** [comment]
@bakie, you most download it http://github.com/ry/http-parser/zipball/459507f534c807d8ba741730fbc36d4b93b133c1 to <code>/home/ikke/Desktop/downloads/michajlo-firesheep-cc98db4/backend/deps/http-parser/</code> 
than edit  <code>/home/ikke/Desktop/downloads/michajlo-firesheep-cc98db4/backend/Makefile.am</code> and replace <code>Linux_x86_64-gcc3</code> to <code>Linux_x86-gcc3</code> and<code>/home/ikke/Desktop/downloads/michajlo-firesheep-cc98db4/xpi/install.rdf</code> change too

**Comment by codebutler** [comment]
Hi everyone,

Firesheep does not currently support Linux. Please follow this issue for updates:
http://github.com/codebutler/firesheep/issues#issue/31

**Comment by benmanns** [comment]
Running `git submodule update --init` fixed this issue for me.
