### ISSUE TITLE
Funky custom tool bar icon explosion.

### ISSUE THREAD

**Issue by unn** [codebutler/firesheep#4]
See screenshot.

http://skitch.com/unncola/d7nf1/firefox

**Comment by Graurk** [comment]
I have almost the same thing in FF 3.6.10 (same problem but different pic)

**Comment by trist** [comment]
I have this too (v3.6.11)

**Comment by ilovesurfing** [comment]
I think its pretty cool looking :)

**Comment by jufemaiz** [comment]
+1 - thought it was rather amusing ;)

**Comment by tomjn** [comment]
+1

**Comment by jjcmontano** [comment]
Same here.  3.6.12

**Comment by codebutler** [comment]
Fixed toolbar icon. Closed by ea1130b8984690a46727c1f61884a25f9a4095e0.
Note that the icon artwork is temporary.
