### ISSUE TITLE
Be aware 802.11 b/g versus n

### ISSUE THREAD

**Issue by SWiT** [codebutler/firesheep#41]
_headslap_
I just got firesheep working on another pair of systems that I was having trouble with.  I forgot about 802.11b/g vs. 802.11n wireless cards.  My firesheep machine has an 802.11b/g wifi card.  My target pc has an 802.11b/g/n card and they were both on an 802.11n wifi access point.  Since the target pc was talking in the 3.2ghz (n) range the firesheep machine couldn't see the traffic with it's 2.4ghz (b/g
) card.  Thank you wireshark for reminding me.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
