### ISSUE TITLE
Only seeing local cookies

### ISSUE THREAD

**Issue by russ7** [codebutler/firesheep#42]
When i start capturing only the log in info from the computer i am using shows up.
The two interface options are the realtek (microsoft packet scheduler), and my wifi card. I have tried both and neither will show me other computer's cookies. please help me see them so i can prank my friends!

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
