### ISSUE TITLE
I am getting my own sessions

### ISSUE THREAD

**Issue by nsim** [codebutler/firesheep#43]
Can anybody tell me, why in an open wifi i am getting just my own sessions? I am working under Windows! Any suggestion?

best regards

**Comment by partridge** [comment]
If you're using Windows 7, this workaround may help you http://www.youtube.com/watch?v=AomuNpnZdLc

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
