### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by skgsergio** [codebutler/firesheep#44]
By default Firesheep sets cookies as domain www.domain.com and some websites ignores them because they only reads domain domain.com
Maybe the domains config option can be used as the correct cookie domain.

Example: http://img251.imageshack.us/img251/2964/exampleez.jpg

**Comment by michaelficarra** [comment]
lol, you didn't censor the <s>`tuenti`</s> in the filter input

_update_: censored my post to protect **skgsergio**'s privacy

**Comment by skgsergio** [comment]
_pokes michaelficarra_ - Are u sure, i dont see that name here? :haha:
