### ISSUE TITLE
Error message when capturing

### ISSUE THREAD

**Issue by curuk** [codebutler/firesheep#45]
I get this error message when I open firefox and enable capturing  

couldn't open device \Device\NPF_{4CF69781-2339-42F6-899AAF3DF7C8BB96}: failed to set hardware filter to promicuous mode

How do I fix this?

**Comment by curuk** [comment]
bump

**Comment by phabeon** [comment]
I get the same msg, using a Toshiba Satellite with an Atheros wifi card. matter of fact Iogged into this site hoping to catch some stuff.. but got nothing..  AnYONE HAVE ANY IDEA ON THIS?  let me know... Thanks   phabeon@hotmail.com

**Comment by Sil3n7** [comment]
Same :(

**Comment by pisto** [comment]
you are running firesheep on windows, and most of windows drivers do not support promiscuous (monitor) mode. Switch to linux or get one of the rare blessed cards that support monitor mode.
