### ISSUE TITLE
No captures !!

### ISSUE THREAD

**Issue by Maximus9** [codebutler/firesheep#46]
I have successfully installed both WinPcap and Firesheep. I am using Firefox v3.6.11
I have tested it on an open Wifi network but it does not capture any cookies (not even local). I tried all options under my the interface option. But no luck.

My options are the following:

MS Tunnel Interface Driver
Gigabit Ethernet Controller
Microsoft....

Please advice, thanx.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
