### ISSUE TITLE
does not compile on linux x86_64

### ISSUE THREAD

**Issue by fallen** [codebutler/firesheep#5]
got this issue : 

fallen@tablet:~/dev/firesheep/backend$ make
rm -f /home/fallen/dev/firesheep/firesheep-backend
g++ -DHAVE_STDARG_H -Wall -include src/config.h -g   -I deps/ -I deps/http-parser -I deps/json_spirit       -lpcap -o /home/fallen/dev/firesheep/firesheep-backend src/main.cpp src/http_sniffer.cpp src/http_packet.cpp deps/http-parser/http_parser.c  
/tmp/cc2OyAQ2.o: In function `main':
/home/fallen/dev/firesheep/backend/src/main.cpp:48: undefined reference to`OSXPlatform::OSXPlatform(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)'
/home/fallen/dev/firesheep/backend/src/main.cpp:63: undefined reference to `OSXPlatform::run_privileged()'
/tmp/cc2OyAQ2.o: In function`~OSXPlatform':
/home/fallen/dev/firesheep/backend/src/osx_platform.hpp:29: undefined reference to `vtable for OSXPlatform'
collect2: ld returned 1 exit status
make: **\* [/home/fallen/dev/firesheep/firesheep-backend] Error 1

**Comment by ignatz** [comment]
the abstract base class UnixPlatform exists. someone needs to implement the virtual functions for a LinuxPlatform class

**Comment by jeremysalwen** [comment]
see: http://github.com/michajlo/firesheep/commit/9bf5b1525eaa34dbe02ad64dc30b5a62ebfe4d43

**Comment by codebutler** [comment]
Firesheep does not currently support Linux. Please follow this issue for updates:
http://github.com/codebutler/firesheep/issues#issue/31
