### ISSUE TITLE
intel wifi link 5100

### ISSUE THREAD

**Issue by Pawz2142** [codebutler/firesheep#52]
The Firesheep does not show the intel wifi link 5100 adapter under interface.

**Comment by binded-zz** [comment]
unplug or disconnect the ethernet  and connect to wifi and use the cain and able from post 
http://github.com/codebutler/firesheep/issues/#issue/49  49 works for me just pick microsoft most likely the first one will be active 

watch that youtube video works for me on a pretty big network

**Comment by binded-zz** [comment]
o but there are some problems with backend quit 1 and such just stop and start cap seems to work 

btw if you choose alot to route you will become the network router hope there not P2P ing

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
