### ISSUE TITLE
Can't find other computers accounts.

### ISSUE THREAD

**Issue by kalkih** [codebutler/firesheep#53]
I have the newest Firefox and Wincap versions and i find my self when logging in on my computer but if someone on another computer logging in on facebook or any other site i cant see them. The interface i can choose from are my Realtek PCI-E Gigabit ethernet and two different Microsoft. One of the Microsoft interface works but i can only see my own computer. If i choose the two other interfaces i cant see anything at all.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
