### ISSUE TITLE
Log in error

### ISSUE THREAD

**Issue by MistahCheese** [codebutler/firesheep#54]
I can catch the accounts and see them, and when I try to log in as them it sends me to the site, but it says that I'm not logged in. Am I doing something wrong? I'm running this on Mac OSX 10.6.4 in firefox 3.6.11

**Comment by Stephen-m** [comment]
Which website, we're talking about?

--Stephen

**Comment by newtonisawesome** [comment]
i have the same problem on facebook, google and yahoo

**Comment by meatspin** [comment]
Me too. Haven't been able to test any more than newtonisawesome so I don't know if it's only with these handlers or all of them.
For me it says "error" in bold italics as the account name and the name of the site underneath. Clicking on the session takes me to the login page of the Site. I'm pretty sure this is the same error.

In case this helps find the cause: local sessions show up fine and if I use internet sharing to share the connection from my tethered iPhone I can capture cookies from people logging into that network fine.

Mac OS X 10.6.4, FF 3.6.12, Card: AirPort Extreme  (0x14E4, 0x88), Firmware: Broadcom BCM43xx 1.0 (5.10.91.27)

**Comment by DeliriousD** [comment]
Bump

...any solution to this problem yet?
