### ISSUE TITLE
Problem, Error in Start Captured/Stop Captured

### ISSUE THREAD

**Issue by marcomix** [codebutler/firesheep#55]
## Couldn't open device \Device \NPF_{C701C0BCSD35/4669/991D/315BEF869A24}: failed to set hardware filter to promiscuous mode.

Exception... "Component returned failure code: 0x80004005(NS_ERROR_FAILURE)[IMozPopenProcess.Stop]" nresult: "0x80004005(NS_ERROR_FAILURE)" location: "JS frame :: file:///C:...etc.../Mozilla/Firefox/Profiles/cci7u51v.default/extensions/firesheep@codebutler.com/modules/FiresheepSession.js ::anonymous :: line 78" data: no

I have this problem in 'Start Capturing' when i use the interface: Atheros AR5006EG Wireless Network Adapter (Microsoft's Packet Scheduler)

But when i use the interface: NVIDIA nForce MCP NEtworking Adapter Driver (Microsoft's Packet Scheduler), i have a another problem in 'Stop Capturing': Backend exited with error 1

I have windows XP and Mozilla Firefox 3.6.12

Why?!
HELP! please!

**Comment by marcomix** [comment]
I think the first problem is causes by the wireless card. WinPCap does not work if:
http://www.winpcap.org/misc/faq.htm#Q-16
See Question 16. 

Required the adaptor wireless USB.

Or No?

**Comment by yooperjb** [comment]
marcomix is most likely correct. The issue probably lies in your wireless card is unsupported. My internal card on my toshiba has a similar failure, but when I put in my Buffalo wireless card everything worked fine.

**Comment by marcomix** [comment]
It's ok! The problem is WIRELESS CARD, because doesn't support the promiscue mode. The promiscue mode is necessary to capture packets with informations. Threfore, we have to buy an external network adapter (USB) that supported the promiscue mode.

But, now i've a another problem!
When i use facebook with my PC portable, firesheep capture the login, but if i use facebook with my second notebook, my PC portable (with firesheep) don't capture.
Why? 

PS.

Both PC refer to the same router!
My first pc use the external card wireless, and the second pc use the internal card wireless. 

NB. I'm italian, sorry for my language.

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
