### ISSUE TITLE
couldn't get netmask en0: en0: no IPv4 address assigned?

### ISSUE THREAD

**Issue by egranola** [codebutler/firesheep#56]
I got all the way to here what am I supposed to do once i get to this part?

**Comment by codebutler** [comment]
Hello,
I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep
Thanks for your interest in Firesheep!

**Comment by sekati** [comment]
same here - mac snow leopard 10.6
