### ISSUE TITLE
Mac to Windows, can it capture?

### ISSUE THREAD

**Issue by egranola** [codebutler/firesheep#58]
alright, so i tried it on myself a few times and it went good, then i tried it against a hp running windows 7 from my mac running OSX 10.6.4 and it wouldn't go. does this have to do with the e0 and e1 in the preference pane? one said airport so can only macs do it to macs and pcs to pcs?

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  
http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
