### ISSUE TITLE
Mac os - finding only local sessions

### ISSUE THREAD

**Issue by kolinko** [codebutler/firesheep#59]
Hi,
I installed firesheep on a Macbook 3,1 with Snow Leopard 10.6 and Firefox 3.6.12.
Firesheep starts, I choose Airport adapter, but only local cookies are found :/

Any suggestions? is it possible that this deosn't work with my airport chip?

Cheers

**Comment by codebutler** [comment]
Hello,

I'd like to keep the GitHub Issue tracker reserved for bug reports and ask that you please move all other discussions here:  http://groups.google.com/group/firesheep

Thanks for your interest in Firesheep!
