### ISSUE TITLE
$(DEST) problem in backend Makefile

### ISSUE THREAD

**Issue by fallen** [codebutler/firesheep#6]
$(DEST) is empty in backend Makefile, so the mkdir -p $(DEST) fails, i removed the lines with $(DEST), maybe there is something wrong about $(DEST)

**Comment by obook** [comment]
Same here.
autogen don't set $(DEST) for Linux platform.
A README-LINUX file will be great.

For instance, I can not compile for this reason and miscellaneous wrong headers path.

**Comment by codebutler** [comment]
Firesheep does not currently support Linux. Please follow this issue for updates:
http://github.com/codebutler/firesheep/issues#issue/31
