### ISSUE TITLE
Wont load up

### ISSUE THREAD

**Issue by VenomousFire** [codebutler/firesheep#60]
Whenever I bring Firesheep into view firefox stops responding and stays like that until  I manually end the backend process, which obviously renders the addon inoperable.

Windows 7 Home Premium 64 bit
Firefox 3.6.11 x86
Also on Firefox 3.6.12 x86

Any other info needed will be gladly given. Thanks for the time to look at this issue

**Comment by codebutler** [comment]
Havent seen this problem myself. This happens as soon as you view the sidebar, before clicking "Start Capture"?

**Comment by codebutler** [comment]
Closing this due to lack of response.
