### ISSUE TITLE
firesheep not compatible with F.F 3.5.5 and 3.6 why??

### ISSUE THREAD

**Issue by Tanny** [codebutler/firesheep#61]
i got an error while installing this
please help friends

**Comment by Stephen-m** [comment]
Hey Tanny

What OS do you use and what error do you get?

--Stephen

**Comment by Tanny** [comment]
window 7 32bit
the error says
"Firesheep 0.1 could not be installed because it is not compatible with Firefox 3.5.5"

**Comment by miroadamy** [comment]
Same happened on OS-X 10.6.4, Firefox 3.6.6

**Comment by Stephen-m** [comment]
I use Windows 7 64-bit
Firefox 3.6.11 and have no problems.

Why didn't you upgrade Firefox to the latest version?

**Comment by Tanny** [comment]
My friend i have used on both versions... And got same error...

**Comment by Tanny** [comment]
I will try again when i reach home tomorrow and post the result.... As i can remember i am using 3.6.6.... Will try on 3.6.11

**Comment by miroadamy** [comment]
My bad. I tend to rely on OS-X notification about new version and have not got any. Installed on 3.6.12 - works fine.
