### ISSUE TITLE
Backend exited with error 1.

### ISSUE THREAD

**Issue by jtecj** [codebutler/firesheep#71]
When I start capturing it will not pull up any cookies, when I click stop capturing it gives me the error "Backend exited with error 1."  I have it showing up fine in the Firefox interface, using FireFox3.6.10.  Have downloaded and installed WinPCap.

**Comment by MrHyde27** [comment]
I too, have been having this issue. I'm running a Windows 7, 64 bit OS running the latest versions of Winpcap and Firefox. I also have a fairly standard Realtek wireless card in my machine. Hoping for a fix very soon!

**Comment by mh123lol** [comment]
any error that pops up is not a big deal, at least when app does its job... btw this error is common and doesnt affect add-on. Read how to use firesheep on windows 7, its not one click thingie...

**Comment by karenerobinson** [comment]
This is happening for my friend running windows vista.  He gets that error on stop capturing.  He's also not seeing any cookies, even when they show up on my firesheep sidebar (we're on the same network).

**Comment by ProjectEvil** [comment]
I have a similar situation on xp 32-bit
installed winpcap, then firesheep and get the "backend exited with error 1."
