### ISSUE TITLE
Nothing happens when I click on start capturing on firesheep

### ISSUE THREAD

**Issue by sushi25x** [codebutler/firesheep#74]
I have installed firesheep and it appears as a sidebar but when i click on "start capturing" after logging onto facebook, there are no accounts that appear on the side. I know that there should be coz there are people on facebook right next to me, yet i still dont see them on the sidebar thing..

**Comment by mh123lol** [comment]
chose correct interface

**Comment by codebutler** [comment]
Hi, please use the discussion group for non-technical questions.
http://groups.google.com/group/firesheep

Thanks.
