### ISSUE TITLE
Non-tech guy can't get started

### ISSUE THREAD

**Issue by patgordon88** [codebutler/firesheep#75]
I tried to download the firesheep for testing and better knowledge on security but can't get it working. I am on a windows XP using firefox. Started out downloading the Wincap then firesheep-0.1-1.xpi and get the error message "application not found". Am I missing a step here? I am new to open source/ tech stuff so I wouldn't be surprised if I messed something up. Any help would be great thanks.

**Comment by codebutler** [comment]
Please use the discussion group for non-tech questions:
http://groups.google.com/group/firesheep
- Eric
