### ISSUE TITLE
Interface unavailable in Windows 7 x86

### ISSUE THREAD

**Issue by taylorchase** [codebutler/firesheep#77]
In firesheep preferences I am unable to select an interface to capture from. Shows the drop down box but no interface appears in the box for me to select.

**Comment by taylorchase** [comment]
I am able to select an interface after running Firefox in Windows XP Compatibility Mode but still cannot capture data and backend exits with error. Tried my bcm4311 and rt73

**Comment by codebutler** [comment]
Hm, does your windows user account not have administrator privileges? That's all I can think of.

**Comment by taylorchase** [comment]
I have full Admin rights. I can see the interface only under XP compatibility mode
