### ISSUE TITLE
Airpcap

### ISSUE THREAD

**Issue by rmura** [codebutler/firesheep#78]
When I try Firesheep with an Airpcap adapter, I get the following error message: Couldn't open device \.\airpcap00: Error opening adapter: the system cannot find the device specified. (20)

The adapter is working fine. Airpcap drivers installed. 

Any insights ?

**Comment by vegetarian-and-loving-it** [comment]
The problem might be that the capture device has the wrong handle.  I fixed this problem but now I have a different problem.  I'll tell you how to get beyond this roadblock and hopefully you won't get the one I'm up against.

  -Open Wireshark and go to the menu item Capture --> Interfaces
  -Click the details button on the row for AirPcap
  -Write down the entry for "Interface."  Mine was something like \.\airpcap00 (the # of slashes is important)
  -Close wireshark and open firefox.  At the bottom of the firesheep sidebar, click the gear and select preferences
  -Go to the capture tab and select the AirPcap interface.  Close the preferences box.
  -Go to the URL    about:config     and accept the warning that you'll be careful
  -Find the entry for   firesheep.capture_interface    right click and modify to exactly what it was named in wireshark
  -Close firefox and re-start

This fixed the inability to open the device but now I'm fighting with an error that it doesn't think AirPcap is an ethernet device.  If anyone can help me here, that would be great.

If this was any help, I'd love for you to join me in celebrating meatless Mondays  http://www.meatlessmonday.com

**Comment by nyc213** [comment]
Were you by any chance able to resolve the airpcap is not an ethernet device error? I'm coming across the same issue and would greatly appreciate any insight you might be able to share.  

Thanks.
