### ISSUE TITLE
ReferenceError: Cc is not defined

### ISSUE THREAD

**Issue by ericgross** [codebutler/firesheep#8]
Running Windows 7 x86-64 and I get this error when loading the plugin UI.

**Comment by darcybross** [comment]
I am having this issue also using Windows XP, FF 3.6.11

**Comment by darcybross** [comment]
_slaps head_ -- Did you install this: http://www.winpcap.org -- It says you need it on the initial Firesheep page. If I had read the direction properly I'd have caught it the first time. Works great for me now.

**Comment by DaDubbs** [comment]
I had the same issue, I had to reinstall WinpCap to get it to work.  I had the software installed already.  Firesheep may need the 4.12 version of winpcap

**Comment by Satorin** [comment]
I'm using Windows XP Home Edition, running FF 3.6.11. I've installed 4.12 version of WinpCap first before installing firesheep but I still get the said error message. No luck in reinstalling WinpCap either.

**Comment by YonatanAmir** [comment]
This issue is unresolved on FF3.6.11 on Windows XP SP3 w/ NOD32 4 enterprise.

**Comment by madgrad2002** [comment]
I posted this on the other issue, but will repeat it here.  For those of you having problems with the ReferenceError, you might want to look into your firewall.  I don't know enough about the problem to help, but I had the same issue with Comodo.  I removed the firewall and everything worked.  Then I reinstalled it (after everything was verified) and it continued to work.

**Comment by Satorin** [comment]
I've tried, but it still doesn't work. (Uninstalling everything and then reinstalling WinpCap, firesheep and then KIS) I'm using Kaspersky Internet Security 2011, and I forgot to mention that I'm on SP3 as well.

**Comment by Satorin** [comment]
Has anybody who had this problem managed to resolve it yet? I still get the error even after re-installling everything (FF, WinpCap and firesheep) and upgrading FF to 3.6.12.

**Comment by LucasEmanuel-zz** [comment]
I have the same problem, and I get several other reference errors to. If i try to go to settings i get another, and another if i go to another tab.

Im using 
Windows 7 x64 Ultimate
FireFox 3.6.11

**Comment by marcohoule** [comment]
I think the card is the problem , if i disable the card and put another one , it's kinda working except that my other card seems not working in promiscuous mode :(

**Comment by pisto** [comment]
I have had the same problem on Linux 64 bit (Ubuntu 10.04), and I've succesfully solved it with a little hack. The problem is in the code that lists the network interface: if it fails to get the vendor of a articular devices, a runtime exception is thrown, which causes the backend to abort, even if I can hardly say that the problem is fatal. You can check if the problem is this one on your machine by running the backend with the --list-interfaces command. On my configuration, it fails when fetching the vendor of the virtual adapter of virtualbox.
So, the quick fix is changing a little thing in backend/src/linux_platfrom.cpp: line 48, "throw ex;" in something less harmful as "return string("ERROR");".

**Comment by codebutler** [comment]
Could someone on windows who's having this problem please try running `firesheep-backend.exe --list-interfaces` using a command prompt from within the extension directory and let me know what happens?

**Comment by fragioud** [comment]
The result of command is:

{"\\Device\\NPF_\{464E5239-5533-4983-B0C2-E3AAB20EC96C\}":{"name":"Realtek
 PCIe FE Family Controller","type":"ethernet"},"\\Device\\NPF_\{541F075A-98
CE-49E1-AB32-B3C6AF51B9FD\}":{"name":"3DSP USB Wireless A+G Notebook Adapter","type":"ethernet"}}

I 'm running windows 7 32bit with firefox 3.6.12 if it helps...

**Comment by pflammertsma** [comment]
I'm getting the exact same symptoms as fragioud. Specifying `--list-interfaces` gives:

```
{"\\\\Device\\\\NPF_\\{3AF939B4-B6F5-4984-8061-9BE037A1E297\\}":
{"name":"Microsoft","type":"ethernet"},
"\\\\Device\\\\NPF_\\{49B8C35F-933F-49F4-B7A6-C475DD91D908\\}":
{"name":"Hamachi Virtual Network Interface Driver","type":"ethernet"},
"\\\\Device\\\\NPF_\\{53E90C29-686B-4DBA-84FE-A4397FE5BB84\\}":
{"name":"Microsoft","type":"ethernet"},
"\\\\Device\\\\NPF_\\{D820294F-BDF6-41D0-8721-DB7032D06CF5\\}":
{"name":"Marvell Yukon Ethernet Controller.","type":"ethernet"}}
```

I'm using Fx 4b7 or Fx 3.6.12 with WinPcap 4.12 on Windows 7 Professional.

**Comment by four43** [comment]
On Ubuntu 10.10 x64, running Firefox 3.6.12, I ran:
     /.mozilla/firefox/[PROFILE NAME]/extensions/firesheep@codebutler.com/platform/Linux_x86_64-gcc3$ sudo ./firesheep-backend --list-interfaces

Returns:
error: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Hal was not provided by any .service files
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct NULL not valid
Aborted (core dumped)

EDIT: lspci returns this for network devices:

```
 03:00.0 Network controller: Intel Corporation WiFi Link 5100
 06:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168B PCI Express Gigabit Ethernet controller (rev 02)
```

I hope that helps, thanks.

**Comment by solman** [comment]
I have the previously described issue under Windows 7 and FF 3.6.13 as well. Any resolution hint so far?

**Comment by cardassian-tailor** [comment]
im having the same issue, cc not defined, ubuntu 10.10 firefix 3.6 
cant get around the error.

**Comment by TrivialPursuit** [comment]
Had the same problem on Asus eeepc 701 , Leeenux 4.1 extended, Ubuntuzilla.
Followed pisto's advice;

So, the quick fix is changing a little thing in backend/src/linux_platfrom.cpp: line 48, "throw ex;" in something less harmful as "return string("ERROR");".

Build the firesheep again;

./autogen.sh

make

firesheep-backend--list-interfaces returned

terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not initialize connection to hald, is it running?

Then I noticed hal was missing so I DL'd it and ran it;

apt-get install hal

hald

now firesheep backend--list interfaces returns;

{"wlan0":{"name":"Atheros Communications Inc. AR5001 Wireless Network Adapter","type":"ieee80211_monitor"},"eth0":{"name":"Atheros Communications L2 100 Mbit Ethernet Adapter","type":"ethernet"}}

and firesheep finds my interfaces and does not report ReferenceError: Cc is not defined anymore!

Problem solved, thanks pisto!

**Comment by JermainMX** [comment]
Hi, 
Had the same problem to solve, in the Device Manager disable all network adapters, leaving active only my wireless card. I hope someone else will serve
