### ISSUE TITLE
Firesheep does not work on Iceweasel (type Linux_x86-gcc3)

### ISSUE THREAD

**Issue by guysoft** [codebutler/firesheep#82]
Hey, installation gives out the following error on installation:

"Firesheep" could not be installed because it is not compatible with your Iceweasel build type (Linux_x86-gcc3). Please contact the author of this item about the problem.

**Comment by codebutler** [comment]
What version?

**Comment by codebutler** [comment]
Wait, to be clear, you're building this from source right? The latest XPI does not include Linux support, as explained on the website.

**Comment by guysoft** [comment]
version 0.1-1
Would it work if compiled?
It seems the xulrunner-1.9.2-dev is not in Debian.

**Comment by codebutler** [comment]
Please re-open this issue after Linux is officially supported if you still have problems.
