### ISSUE TITLE
Does not start in 3.6.12

### ISSUE THREAD

**Issue by mkonicek** [codebutler/firesheep#84]
Failed to load XPCOM component: C:\Users...\AppData\Roaming\Mozilla\Firefox\Profiles\xd6q1rht.firesheep\extensions\firesheep@codebutler.com\components.DS_Store

Failed to load XPCOM component: C:\Users...\AppData\Roaming\Mozilla\Firefox\Profiles\xd6q1rht.firesheep\extensions\firesheep@codebutler.com\platform\WINNT_x86-msvc\components\mozpopen.pdb

**Comment by codebutler** [comment]
Hm, maybe it's not compatible with roaming protocols? Could you try creating a local account?

**Comment by codebutler** [comment]
Closing due to lack of response.

**Comment by mkonicek** [comment]
Hi, sorry, I did not know how to create a Firefox "local account".

**Comment by gpaharenko** [comment]
Hi! I have load problem as well:
  Failed to load XPCOM component: C:\Documents and Settings\username\Application Data\Mozilla\Firefox\Profiles\88964rwb.default\extensions\firesheep@codebutler.com\platform\WINNT_x86-msvc\components\mozpopen.pdb

**Comment by codebutler** [comment]
Sorry, I didn't read this very carefully the first time. Errors about pdb/DS_Store files can be ignored. If things aren't working, something else is wrong.
