### ISSUE TITLE
Ask for root password via X

### ISSUE THREAD

**Issue by shtrom** [codebutler/firesheep#85]
Currently, when Firefox runs as a non-root user, it queries for the superuser's password on the console. It would be better if the query was made graphically. Even better would be using some ss-askpass provider (which sudo can do by default).

Also, and FYI, I built the XPI from the source tree on x86_64 (ArchLinux), and it appears to work just fine.

**Comment by codebutler** [comment]
You're probably missing Qt/GTK PolicyKit support. On Ubuntu (10.10) under GNOME this works properly.
