### ISSUE TITLE
Error in configure while running autogen.sh

### ISSUE THREAD

**Issue by psynaptic** [codebutler/firesheep#87]
I followed the steps as outlined in the readme but I get the following:

http://pastebin.com/HfeCDKHB

**Comment by philk2010** [comment]
Me too.  Can anyone assist with this?

**Comment by philk2010** [comment]
to make it even easier to diagnose.... the errors boil down to:

line 3262: syntax error near unexpected token `MOZ,'
line 3262:`    PKG_CHECK_MODULES(MOZ, libxul >= 1.9.2)'

Which completely beats me.  Code seems alright... is there some corruption in the download (I got some corrupted source downloads a couple months back, but this dl seemed better)?

Anyways, any help would be greatly appreciated!

**Comment by krinndnz** [comment]
I also am experiencing this error while building.  Not to belabor the obvious, but I guess that make isn't outputting a correct configuration for some reason.

**Comment by codebutler** [comment]
Fix OS X build problems. Closed by 02d6e5d675327abbf02ac54dc5ed52928200d2bb.
