### ISSUE TITLE
TypeError: result is undefined

### ISSUE THREAD

**Issue by Koukin** [codebutler/firesheep#89]
Hello, 
I compiled and installed firesheep without any errors. But when I start to capture I see this:
http://imgur.com/hsCJN.png

Obviously there's something wrong here, when I try to connect to one of those sessions I get this error:
http://imgur.com/S3LOr.png

Has this happened to anybody else?
Thanks in advance.

**Comment by darylseah** [comment]
I'm getting the _exact_ same error as you. Been wondering if I was the only one.

Using a MacBook Pro and FireFox 3.6.12 with all other plugins disabled.

**Comment by codebutler** [comment]
Hm.. Anything suspicious in the error console? (Tools -> Error Console)

**Comment by darylseah** [comment]
Nothing that I find suspicious. Managed to get it working though. Apparently I didn't disable _all_ the other plugins - there were a few stragglers. After doing that, the error entries on the sidebar still show up, but a couple of valid logins were captured as well. 

Must have been a conflict somewhere. Kinda lazy to identify which plugin was the troublemaker.  :)
