### ISSUE TITLE
Not compatible with FileVault (OS X --fix-permissions error)

### ISSUE THREAD

**Issue by robotskirts** [codebutler/firesheep#9]
When you click Start Capturing a dialog pops up asking for you password so firesheep-backend can have the system.privilege.admin right. After entering the password and clicking Ok you get an error that says "Run --fix-permissions first". I haven't been able to do this successfully.

OS X 10.6.4
FF 3.6.11

**Comment by gregcarlin** [comment]
I didn't get that with FF 3.6.11 on 10.6.4 instead for me it just didn't load

**Comment by matt-** [comment]
The only way i could get this to work is run firefox as root: 

sudo /Applications/Firefox.app/Contents/MacOS/firefox-bin

**Comment by astrofrog** [comment]
I have the same issue - same Firefox and OS X versions.

**Comment by codebutler** [comment]
Hey - A few people have suggested that this error is caused by File Vault being enabled - are you all using that?

**Comment by astrofrog** [comment]
Yes, I am using FileVault

**Comment by robotskirts** [comment]
Whoops. I accidentally closed this and there doesn't seem to be a reopen.

Yes, I am using FileVault.

**Comment by gregcarlin** [comment]
I am not using FileVault and I got it to work so maybe it is FileVault

**Comment by davidaurelio** [comment]
A workaround is to move the extension directory from your user’s Firefox profile into the application directory (/Applications/Firefox.app/Contents/MacOS/extensions/).

**Comment by consti** [comment]
Another workaround is running Firefox with another user through the terminal (I am running with root). You'll then have to reinstall the extension:

1) Start Firefox with another user
sudo /Applications/Firefox.app/Contents/MacOS/firefox-bin

2) Install extension, close Firefox and restart as other user (e.g. sudo).

That fixed it for me

**Comment by mjstarks** [comment]
FYI, I am using the latest version of firefox and Mac OS X and have never used filevault, I still get the fix permissions error.

**Comment by abraham** [comment]
A temporary work around is to use it in the guest account.

You can also move the firesheep extension to the global Firefox extension directory: http://securitymusings.com/article/2240/firesheep-on-a-mac-running-filevault

**Comment by codebutler** [comment]
Added Filevault workaround. Closed by a50e9fa2bd29b840e226ee92eedf3689f134270a.
