### ISSUE TITLE
unable to load xpcom

### ISSUE THREAD

**Issue by gpaharenko** [codebutler/firesheep#91]
Hi! I have trouble loading XPCOM. Firefox 3.6.12. winXP:
It appears for a second at the beginning and then dissappears
Failed to load XPCOM component: C:\Documents and Settings\username\Application Data\Mozilla\Firefox\Profiles\88964rwb.default\extensions\firesheep@codebutler.com\platform\WINNT_x86-msvc\components\mozpopen.pdb

**Comment by codebutler** [comment]
This error is a false alarm, so your problem must be something else...
