### ISSUE TITLE
Not Capturing anyone, not even myself!

### ISSUE THREAD

**Issue by Jimmykaboots** [codebutler/firesheep#92]
Hi everyone, I recently downloaded this wonderful program and I can't wait to try it out! However, I have not been able to get it to work! I downloaded wincap, then firefox, then the add on. But when I hit start capture, nothing happens. Even if I go on facebook on my chrome browser I can't see anything come up. In the preferences there is Microsoft and Atheros L1C PCI-E Ethernet Controller. Also, I am running an acer aspire one netbook and windows 7 starter package. Does anyone have any idea how I can fix this? Thanks for your time!

**Comment by vadamee1996** [comment]
i have the same problem :/

**Comment by Jimmykaboots** [comment]
Haha doesnt it suck! Argh!
