### ISSUE TITLE
Winpcap Hardware Description not Enought

### ISSUE THREAD

**Issue by txomon** [codebutler/firesheep#93]
Hello, I have tryed Firesheep, but it has a problem. If u have several Network cards, It uses "Descripition" and in som of them, only appears "Microsoft". I would suggest to put MAC address as descriptor and also the IP it actually has

**Comment by orinxxx** [comment]
Where do you put MAC Address as descriptor and IP?

Thanks

**Comment by txomon** [comment]
¿? I meant that it would be a good Idea to put that info instead or with the Network card, so that we can difference it
