### ISSUE TITLE
Build Firesheep on Fedora systems

### ISSUE THREAD

**Issue by gaveen** [codebutler/firesheep#95]
Since Firesheep now has basic support for Ubuntu, I tried to build it from 3967eca65cee937375b9e8c0a03256a92b52a3e3 on a Fedora 14 (i686) system.

I was unsuccessful and make exits with the following:
make[1]: Entering directory `/home/gaveen/Software/Builds/firesheep/backend'
make[1]: *** No rule to make target`deps/http-parser/http_parser.c', needed by `../xpi/platform/Linux_x86-gcc3/firesheep-backend'.  Stop.
make[1]: Leaving directory`/home/gaveen/Software/Builds/firesheep/backend'
make: **\* [all-recursive] Error 1

I used Ubuntu dependencies as a starting point and installed the following software (plus their dependencies) before running the autogen.sh:
libtool-2.2.10-3
autoconf-2.66-2
libpcap-devel-1.1.1-1
boost-devel-1.44.0-4
boost-mpich2-devel-1.44.0-4
boost-openmpi-devel-1.44.0-4
hal-devel-0.5.14-5
xulrunner-devel-1.9.2.13

**Comment by eschnou** [comment]
Found the solution here (with more hints on building on Linux)
http://blog.macuyiko.com/2010/11/compiling-firesheep-on-linux.html

Just run a sub-module update and it will work:
git submodule update --init
