### ISSUE TITLE
issue with connecting to other computers

### ISSUE THREAD

**Issue by fritt91** [codebutler/firesheep#98]
okey, im not a big mac expert.. can someone tell my why im only are capturing my own facebook etc? and tell me how to fix it! please..=)

**Comment by vadamee1996** [comment]
there seems to be a problem with the wireless on fire sheep most people connect to there own computers and even if you could connect to the router most ban promiscuous behavior like this, theirs a forum with more information called limited interface options labeled as [BUG]

**Comment by chloe99** [comment]
Firesheep needs to be able to see the traffic. So works best with OPEN wifi, as in no password used, no WPA, no WEP no nothing. Think Starbucks.

It will however also work if you manage to route traffic through you, for example via ARP poisoning.
